backend/src/main/java/com/woowacourse/naepyeon/TestDataInit.java, backend/src/main/java/com/woowacourse/naepyeon/controller/MessageController.java, backend/src/main/java/com/woowacourse/naepyeon/controller/RollingpaperController.java, backend/src/test/java/com/woowacourse/naepyeon/acceptance/TeamAcceptanceTest.java
- 회원 및 모임은 1차 데모데이 구현사항에 해당되지 않는다.
- 회원, 모임은 백엔드에서 구현한 더미데이터 https://github.com/woowacourse-teams/2022-nae-pyeon/issues/6 을 사용하도록 변경한다.
이 더미데이터는 이후에 회원, 모임이 본격적으로 구현되면 삭제한다.
close #41
=> feat: 컨트롤러에 더미데이터로 응답값을 전달하도록 변경한다.

backend/src/test/java/com/woowacourse/naepyeon/acceptance/AcceptanceTest.java
`@GeneratedValue`를 auto인 상황에서 IDENTITY로 수정하고 테스트 코드를 돌렸을때
email 유니크 제약조건으로 인한 에러가 발생했습니다.
`@GeneratedValue`가 auto일 경우 h2 db에서는 SEQUENCE 전략이 선택됩니다.
em.persist()로 member를 영속화할 때 id 생성을 위해서 DB가 관리하는 SEQUENCE OBJECT에서 id 값을 가져오는데
SEQUENCE 전략은 굳이 INSERT 쿼리가 DB에 나가지 않아도 id 값을 알 수 있으므로 AUTO 일 땐 INSERT 쿼리가 나가지 않습니다.
그래서 db를 거치지 않아서 email 유니크 제약조건이 걸리지 않았던 것입니다.
gradle로 테스트 코드가 동작되면 테스트 격리가 정상적으로 이루어지지만 Junit으로 테스트 코드가 동작되면 테스트 격리가 정상적으로
이루어지지 않는 현상이 있습니다. 일단은 gradle이나 Junit으로 테스트 코드가 동작되더라도 깨지지 않는 형태로 수정하였습니다.
`@DirtiesContext(classMode = ClassMode.AFTER_EACH_TEST_METHOD)`로 변경하면 gradle, Junit에서도 다 성공적으로 동작됩니다. 다만 DB가 변경되더라도 해당 테스트코드에 대한 변경이 없게 하려고 `@AutoConfigureTestDatabase`를 유지하는 방안으로 했습니다.
---
+ `@AutoConfigureTestDatabase`: 설정해놓은 DB가 아닌 in-memory DB를 활용해서 테스트가 실행됩니다.
+ …
=> fix: @GeneratedValue를 IDENTITY로 수정했을 때 테스트 격리를 시킨다.

backend/src/main/java/com/woowacourse/naepyeon/domain/Message.java, backend/src/main/java/com/woowacourse/naepyeon/domain/TeamMember.java
Message, TEAM_MEMBER에서 `cascade=CascadeType.REMOVE` 옵션 삭제
- 옵션이 걸려있을 경우, 메시지를 삭제할 때 롤링페이퍼도 삭제됨. (부모가 삭제되면 자식도 삭제됨. 이 옵션을 부모에 걸어야 되는데 우리는 Message에 걸었음.)
- 단방향 연관관계여서 rollingpaper에 걸지 못했음.
- 논리적 삭제를 고려하면 옵션을 해제하는 게 맞음.
- 메시지가 2개 이상일 때 삭제하려 하는 경우, 다른 메시지가 이미 존재하기 때문에 삭제가 되지 않았던 것. 
- 논리적 삭제를 적용하자 vs 양방향 연관관계로 `cascade=CascadeType.REMOVE`를 적용하자
- 삭제 정책이 정해지면, 설계 방향이 잡히고 인수 테스트를 명확하게 작성할 수 있을 듯함.
close #52
=> fix: 메시지 삭제 시, 롤링페이퍼와 연관해서 삭제 관련된 버그 수정

backend/src/main/resources/application.yml
- OSIV 옵션을 해제했다.
```yml
jpa.open-in-view: false
```
[참고 링크](https://ykh6242.tistory.com/entry/JPA-OSIVOpen-Session-In-View%EC%99%80-%EC%84%B1%EB%8A%A5-%EC%B5%9C%EC%A0%81%ED%99%94)
- 영속성 컨텍스트를 컨트롤러, 뷰 영역에까지 끌고 오지 않음.
- 트랜잭션을 서비스 레이어에서까지만 관리할 수 있음.
close #34
=> feat: osiv 옵션을 해제한다.

frontend/src/components/TeamJoinModalForm.tsx, frontend/src/components/TeamJoinSection.tsx, frontend/src/mocks/handlers.js, frontend/src/pages/TeamDetailPage.tsx
- 모임 상세보기 페이지에서 모임 단건 조회 요청(GET)을 보내고 응답을 처리한다.
- 모임 상세보기 페이지에서 모임의 롤링페이퍼 목록 조회 요청(GET)을 보내고 응답을 처리한다.
- 모임 상세보기 페이지에서 모임 가입 요청(POST)을 보내고 응답을 처리한다.
- 모임 단건 조회 요청(GET) mocking 코드를 작성한다.
- 모임의 롤링페이퍼 목록 조회 요청(GET) mocking 코드를 작성한다.
- 모임 가입 요청(POST) mocking 코드를 작성한다.
close #119
=> feat: 모임 상세보기 페이지 API 요청 및 응답 처리 로직 구현

backend/src/main/java/com/woowacourse/naepyeon/controller/MemberController.java, backend/src/main/java/com/woowacourse/naepyeon/service/MemberService.java, backend/src/test/java/com/woowacourse/naepyeon/acceptance/AcceptanceFixture.java, backend/src/test/java/com/woowacourse/naepyeon/acceptance/MemberAcceptanceTest.java
- 회원 추가
- 회원을 추가하고 검증한다. (회원추가, 단건조회)
- 이미 가입된 회원이 추가되는 경우 예외를 발생한다.
- 회원 가입 시, 회원 이름이 2 ~ 20자 및 한글, 영어, 숫자가 아닌 경우 예외가 발생한다.
- 회원 가입 시, 이메일이 기본 이메일 형식이 아닌 경우 예외가 발생한다.
- 회원 가입 시, 비밀번호가 8 ~ 20자 및 영어, 숫자가 포함되지 않는 경우 예외가 발생한다.
- 회원 조회
- 올바르지 않은 토큰으로 마이페이지를 조회할 경우 예외가 발생한다.
- 존재하지 않는 id로 회원 조회를 하려 하는 경우 예외가 발생한다.
- 회원 수정
- 회원 정보를 수정할 수 있다.
- 올바르지 않은 토큰으로 수정할 경우 예외가 발생한다.
- 회원 수정 시, 회원 이름이 2 ~ 20자 및 한글, 영어, 숫자가 아닌 경우 예외가 발생한다.
- 회원 삭제
- 회원을 삭제할 수 있다.
- 올바르지 않은 토큰으로 삭제할 경우 예외가 발생한다.
- 존재하지 않는 회원을 삭제하려 하는 경우 예외가 발생한다.
확인부탁드립니다!
close #82
=> test: 회원 관련 인수 테스트를 작성한다.

backend/src/main/java/com/woowacourse/naepyeon/controller/MemberController.java, backend/src/main/java/com/woowacourse/naepyeon/controller/RollingpaperController.java, backend/src/main/java/com/woowacourse/naepyeon/controller/dto/RollingpaperCreateRequest.java, backend/src/main/java/com/woowacourse/naepyeon/exception/NotFoundMemberException.java, backend/src/main/java/com/woowacourse/naepyeon/exception/NotFoundTeamMemberException.java, backend/src/main/java/com/woowacourse/naepyeon/exception/UncertificationTeamMemberException.java, backend/src/main/java/com/woowacourse/naepyeon/repository/JpaRollingpaperRepository.java, backend/src/main/java/com/woowacourse/naepyeon/repository/RollingpaperRepository.java, backend/src/main/java/com/woowacourse/naepyeon/repository/jpa/RollingpaperJpaDao.java, backend/src/main/java/com/woowacourse/naepyeon/service/RollingpaperService.java, backend/src/test/java/com/woowacourse/naepyeon/acceptance/AcceptanceFixture.java, backend/src/test/java/com/woowacourse/naepyeon/acceptance/MemberAcceptanceTest.java, backend/src/test/java/com/woowacourse/naepyeon/acceptance/RollingpaperAcceptanceTest.java, backend/src/test/java/com/woowacourse/naepyeon/repository/RollingpaperRepositoryTest.java, backend/src/test/java/com/woowacourse/naepyeon/service/RollingpaperServiceTest.java
close #104 
- 403 Forbidden 
- 4013: 해당 모임에 가입해야 가능한 작업입니다.
- 404 Not Found
- 4012: 해당 모임에 가입되지 않은 회원입니다.
- 해당 회원이 받은 롤링페이퍼 목록 조회 기능 및 api 추가
- 롤링페이퍼 api에서, 모임에 속하지 않은 회원이 작업을 하려 하는 경우 예외를 터뜨리도록 수정
```java
private boolean checkMemberNotIncludedTeam(final Long teamId, final Long memberId) {
final List<Long> joinedTeamsId = teamMemberRepository.findTeamsByJoinedMemberId(memberId)
.stream()
.map(Team::getId)
.collect(Collectors.toUnmodifiableList());
return !joinedTeamsId.contains(teamId);
}
```
```java
if (checkMemberNotIncludedTeam(teamId, loginMemberId)) {
throw new UncertificationTeamMemberException(teamId);
}
if (checkMemberNotIncludedTeam(teamId, memberId)) {
throw new NotFoundTeamMemberException(memberId);
}
```
- service layer에서 `RollingpaperDao`, `MemberDao`를 상태로 갖던 임시작업 수정
- 인수테스트 …
=> feat: 롤링페이퍼 인수 테스트 작성

backend/src/main/java/com/woowacourse/naepyeon/domain/Rollingpaper.java, backend/src/main/java/com/woowacourse/naepyeon/repository/JpaTeamParticipationRepository.java, backend/src/main/java/com/woowacourse/naepyeon/repository/TeamParticipationRepository.java, backend/src/main/java/com/woowacourse/naepyeon/repository/jpa/TeamMemberJpaDao.java, backend/src/main/java/com/woowacourse/naepyeon/repository/jpa/TeamParticipationJpaDao.java, backend/src/main/java/com/woowacourse/naepyeon/service/RollingpaperService.java, backend/src/main/java/com/woowacourse/naepyeon/service/TeamService.java, backend/src/main/java/com/woowacourse/naepyeon/service/dto/RollingpaperPreviewResponseDto.java, backend/src/test/java/com/woowacourse/naepyeon/domain/RollingpaperTest.java, backend/src/test/java/com/woowacourse/naepyeon/repository/TeamParticipationRepositoryTest.java, backend/src/test/java/com/woowacourse/naepyeon/service/RollingpaperServiceTest.java, backend/src/test/java/com/woowacourse/naepyeon/service/TeamServiceTest.java
close #137 
- memberId, teamId로 닉네임을 조회하는 dao 기능 구현
- 서비스 쪽에서 이미 teamId, memberId로 NOT_FOUND, UNCERTIFICATION 에러를 검증해준 후에, 위 로직을 호출하므로 별도의 예외는 두지 않았습니다.
- 서비스 테스트 추가 
-`TeamParticipationRepository` 가 아닌, `TeamMemberRepository` 라는 이름으로 돼있어서 수정했습니다.
=> feat: Feature/137 paper adressee nickname

backend/src/main/java/com/woowacourse/naepyeon/repository/JpaTeamParticipationRepository.java, backend/src/main/java/com/woowacourse/naepyeon/repository/TeamParticipationRepository.java, backend/src/main/java/com/woowacourse/naepyeon/repository/jpa/TeamParticipationJpaDao.java, backend/src/main/java/com/woowacourse/naepyeon/service/RollingpaperService.java, backend/src/main/java/com/woowacourse/naepyeon/service/TeamService.java, backend/src/test/java/com/woowacourse/naepyeon/repository/TeamParticipationRepositoryTest.java, backend/src/test/java/com/woowacourse/naepyeon/repository/TeamRepositoryTest.java, backend/src/test/java/com/woowacourse/naepyeon/service/TeamServiceTest.java
close #144 
- 레포지토리 메서드명 네이밍에 포함된 `joined` 제거
- db 단에서는 해당 멤버아이디가 모임에 가입됐는지 여부는 중요하지 않음. 단순히 memberId로 team을 조회하는 기능에만 집중하는 메서드라 생각.
=> test: 모임 관련 서비스, 레포지토리 테스트 보충

backend/src/main/java/com/woowacourse/naepyeon/NaepyeonApplication.java, backend/src/main/java/com/woowacourse/naepyeon/config/JpaAuditingConfig.java, backend/src/main/java/com/woowacourse/naepyeon/domain/BaseEntity.java, backend/src/main/java/com/woowacourse/naepyeon/domain/Member.java, backend/src/main/java/com/woowacourse/naepyeon/domain/Message.java, backend/src/main/java/com/woowacourse/naepyeon/domain/Rollingpaper.java, backend/src/main/java/com/woowacourse/naepyeon/domain/Team.java, backend/src/main/java/com/woowacourse/naepyeon/domain/TeamParticipation.java, backend/src/test/java/com/woowacourse/naepyeon/repository/MemberRepositoryTest.java, backend/src/test/java/com/woowacourse/naepyeon/repository/MessageRepositoryTest.java, backend/src/test/java/com/woowacourse/naepyeon/repository/RollingpaperRepositoryTest.java, backend/src/test/java/com/woowacourse/naepyeon/repository/TeamParticipationRepositoryTest.java, backend/src/test/java/com/woowacourse/naepyeon/repository/TeamRepositoryTest.java
close #88
- 수정일자를 테스트하기 위해 Entitymanager의 flush 기능이 필요해서 RepositoryTest에 `@Autowired`로 EntityManager를 주입받았으나 아래 사진처럼 빨간줄이 발생하면서 `Could not autowire. No beans of 'EntityManager' type found.`에러 발생
- `@SpringBootTest` 또는 `@DataJpaTest`를 사용하면 EntityManager는 자동으로 스프링 빈으로 관리되기 때문에 `@Autowired`를 사용하면 EntityManager이 호출돼야 정상인데 위처럼 빨간줄이 발생함.
스프링부트 2.7.1 버전의 버그.
1. 스프링부트 버전을 2.6.9 이하로 내리면 해결된다.
2. 해당 빨간줄은 버그일 뿐, 테스트 및 실행에 아무런 문제가 없으므로 무시한다. -> **채택**
=> feat: 생성일자, 수정일자 필드 추가

backend/src/main/java/com/woowacourse/naepyeon/controller/TeamController.java, backend/src/main/java/com/woowacourse/naepyeon/controller/dto/UpdateTeamMemberRequest.java, backend/src/main/java/com/woowacourse/naepyeon/controller/dto/UpdateTeamParticipantRequest.java, backend/src/main/java/com/woowacourse/naepyeon/exception/DuplicateNicknameException.java, backend/src/main/java/com/woowacourse/naepyeon/repository/JpaTeamParticipationRepository.java, backend/src/main/java/com/woowacourse/naepyeon/repository/TeamParticipationRepository.java, backend/src/main/java/com/woowacourse/naepyeon/repository/jpa/TeamParticipationJpaDao.java, backend/src/main/java/com/woowacourse/naepyeon/service/MessageService.java, backend/src/main/java/com/woowacourse/naepyeon/service/RollingpaperService.java, backend/src/main/java/com/woowacourse/naepyeon/service/TeamService.java, backend/src/main/java/com/woowacourse/naepyeon/service/dto/TeamMemberResponseDto.java, backend/src/test/java/com/woowacourse/naepyeon/acceptance/AcceptanceFixture.java, backend/src/test/java/com/woowacourse/naepyeon/acceptance/TeamAcceptanceTest.java, backend/src/test/java/com/woowacourse/naepyeon/repository/TeamParticipationRepositoryTest.java, backend/src/test/java/com/woowacourse/naepyeon/service/TeamServiceTest.java
close #182 
1. 모임 가입 정보 조회 API
2.모임 닉네임 수정 API 구현
- 팀이 가입돼있지 않거나, 팀이 존재하지 않는 경우 예외 발생
- 이미 존재하는 닉네임으로 수정할 경우 아래 예외 발생
=> feat: 모임 마이페이지 기능 구현

frontend/src/context/UserContext.tsx
- UserProvider의 isLoggedIn 초기 상태를 accessToken cookie 존재 여부에 따라 주도록 수정
- UserProvider의 내 정보 조회 요청 성공 응답이 돌아오면 default header Authorization 값을 설정
close #213
=> fix: 자동 로그인 에러 수정

frontend/src/components/MyPagePaginatedMessageList.tsx, frontend/src/components/MyPagePaginatedRollingpaperList.tsx, frontend/src/components/UserProfile.tsx, frontend/src/mocks/dummy/receivedRollingpapers.json, frontend/src/mocks/dummy/sentMessages.json, frontend/src/mocks/handlers/memberHandlers.js, frontend/src/pages/MyPage.tsx, frontend/src/types/index.ts
- 내 정보 조회, 내 정보 수정, 내가 받은 롤링페이퍼 목록 조회, 내가 작성한 메시지 목록 조회 API 로직 MyPage 컴포넌트 내에서 동작하도록 구현
- 받은 롤링페이퍼 목록, 작성한 메시지 목록 페이지네이션 가능하도록 구현
- 내 정보 조회, 내 정보 수정, 내가 받은 롤링페이퍼 목록 조회, 내가 작성한 메시지 목록 조회 API mocking
1. MyPage 페이지 컴포넌트에서 너무 많은 API 요청 로직을 가지고 있어서 자식 컴포넌트에게 분배하면 어떨까 싶어요. 당장 생각해본 방식들은 다음과 같습니다.
- API 변경 없이 자식 컴포넌트로 API 요청 로직을 옮기려면? 페이지 컴포넌트 탭에서 전체 컨텐츠 개수가 필요함, 페이지 컴포넌트에서 Count 상태만 가지고, 자식 컴포넌트(리스트 컴포넌트)에서 setCount만 내려 받아 요청 응답이 돌아왔을 때 해당 상태만 업데이트하는 방법
- 컨텐츠 개수만 돌려주는 API 새로 추가, 마이페이지에서 개수만 가져오고 리스트 컴포넌트 각각에서 목록 조회 API 요청 -> 백엔드 논의 필요
도리 생각은 어떤가요? 의견이나 다른 아이디어 있다면 공유 부탁해요!
2. Axios 에러 처리 로직이 반복되는데, util 함수나 useQuery 또는 useMutation을 커스텀 훅으로 감싸서 분리해보면 좋을 것 같아요.  방법은 조금 더 고민해볼게요.
close #203
=> feat: 마이페이지 API 요청 및 응답 로직 구현

frontend/package.json, frontend/src/App.tsx, frontend/src/components/LetterPaper.tsx, frontend/src/components/RollingpaperMessage.tsx, frontend/src/components/TeamJoinModalForm.tsx, frontend/src/components/TeamRollingpaperList.tsx, frontend/src/components/UserProfile.tsx, frontend/src/context/UserContext.tsx, frontend/src/pages/LoginPage.tsx, frontend/src/pages/MainPage.tsx, frontend/src/pages/MessageDetailPage.tsx, frontend/src/pages/MessageEditPage.tsx, frontend/src/pages/MessageWritePage.tsx, frontend/src/pages/MyPage.tsx, frontend/src/pages/RollingpaperCreationPage.tsx, frontend/src/pages/RollingpaperPage.tsx, frontend/src/pages/SignUpPage.tsx, frontend/src/pages/TeamCreationPage.tsx, frontend/src/pages/TeamDetailPage.tsx, frontend/src/pages/TeamSearchPage.tsx, frontend/yarn.lock
- react-query version 4로 업그레이드
`react-query 3.39.1` -> `@tanstack/react-query 4.0.10`
closed #220
=> chore: react query version 업그레이드

frontend/src/context/UserContext.tsx
UserContext의 내 정보 조회 시 잘못된 Url로 요청을 보내는 문제 발견
- UserContext의 내 정보 조회 API에서 사용하는 axios의 baseUrl 설정이 안 되어있다.
- UserContext의 내 정보 조회 요청 Url이 잘못 설정되어있다.
- UserContext에서 내 정보 조회 시,  baseUrl이 설정되어 있는 axios instance를 사용하도록 변경
- UserContext의 내 정보 조회 요청 Url을 변경
=> fix: UserContext의 내 정보 조회 요청 URL 수정

frontend/src/pages/RollingpaperPage/index.tsx
- LetterPaper에서 messageList prop 배열의 정렬 순서 변경
가장 최근에 작성 메시지가 좌측 상단에, 가장 처음에 작성한 메시지가 우측 하단에 위치합니다. 
(아래 이미지 참고해주세요. 메시지 컨텐츠의 번호가 메시지 작성한 순서입니다.)
<br >
closed #260
=> feat: 롤링페이퍼 메시지 정렬 순서 변경

frontend/src/api/kakaoOauth.ts, frontend/src/mocks/handlers/memberHandlers.js, frontend/src/pages/KakaoRedirectPage/index.tsx, frontend/src/types/oauth.ts
- kakao oauth API 명세 추가에 따라 mocking handler 추가
- kakao oauth api 로직 및 KakaoRedirectPage 내부 로직 전반 수정
<br >
- authorizationCode나 redirectUri를 못 찾아왔을 때 예외 처리를 어떻게 하면 좋을지 고민이에요. 
[해당 부분 코멘트](https://github.com/woowacourse-teams/2022-nae-pyeon/pull/263#discussion_r935529312)로 남기겠습니다.
<br >
closed #259
=> feat: 카카오 로그인 API 명세 변경에 따라 관련 로직 변경

frontend/src/api/team.ts, frontend/src/mocks/dummy/myTeams.json, frontend/src/mocks/handlers/teamHandlers.js, frontend/src/pages/MainPage/index.tsx, frontend/src/pages/MyPage/components/MessageCard.tsx, frontend/src/pages/MyPage/components/MessageList.tsx, frontend/src/pages/MyPage/components/MessageListItem.tsx, frontend/src/pages/MyPage/components/RollingpaperCard.tsx, frontend/src/pages/MyPage/components/RollingpaperList.tsx, frontend/src/pages/MyPage/components/RollingpaperListItem.tsx, frontend/src/pages/TeamSearchPage/index.tsx
- 마이페이지의 내가 받은 롤링페이퍼 목록에서 아이템 클릭 시, 해당 롤링페이퍼 페이지로 이동한다.
- 마이페이지의 내가 작성한 메세지 목록에서 아이템 클릭 시, 해당 메세지가 작성된 롤링페이퍼 페이지로 이동한다.
<br >
- MyPage 내부 컴포넌트에서, types 폴더에 정의해둔 ReceivedRollingpaper, SentMessage 타입을 사용하도록 수정
- RollingpaperCard, MessageCard 내부에 Link 추가
<br >
- RollingpaperList - RollingpaperCard, MessageList - MessageCard 형식인데 Card 대신 ListItem으로 이름을 바꾸는 건 어떨까요? 모양이 기존에 사용하던 Card와는 다르기도 하고, list 태그 내에 있어서 li 태그로 감싸줬더라고요. ([코멘트](https://github.com/woowacourse-teams/2022-nae-pyeon/pull/266#discussion_r935796817) 참고해주세요!)그래서 ListItem으로 네이밍해도 좋을 것 같습니다. 이 부분 도리 의견 들어보고 리팩토링 진행하겠습니다~
<br >
closed #249
=> feat: 마이페이지의 롤링페이퍼/메시지 목록 아이템 클릭 시 페이지 이동 기능 구현

frontend/src/pages/MyPage/index.tsx
- MyPage 내의 react-query 로직의 option에서 placeholderData만 모두 제거했습니다.
<br >
closed #275
=> fix: MyPage API 로직의 placeholderData 제거

frontend/src/pages/MyPage/components/UserProfile.tsx
- 이름 변경 취소 버튼 handler 수정
- 이름 변경시 유저 정보 refetch
유저 정보만을 refetch해오고 있는데요, rollingpaper와 message정보도 refetch하는 것이 좋을지 고민입니다. 우선적으로 사용자의 이름과 두 정보는 연관이 없어 refetch하지 않도록 하였습니다.
closed #274
=> feat: 유저 정보가 변경되면 변경된 정보를 refetch

frontend/src/pages/TeamSearchPage/index.tsx
- query key로 searchKeyword를 두어 생기는 오류 해결
querykey로 searchKeyword를 두어 이 값이 변할때(사용자가 입력할때마다) 다시 값을 가져오는 에러를 해결했습니다. 다만, 앞으로 querykey를 어떻게 두는 것이 좋을지 고민이 됩니다. 검색 버튼을 눌렀을때만 key값을 추가할 수 있는지와 같은 방법은 더 찾아보도록 할께요🤪 (앞으로 코드리뷰 하고도 pull받아서 실행시켜보도록하겠습니다....ㅎ)
closed #300
=> feat: 검색창 오류 해결

frontend/src/mocks/handlers/teamHandlers.js, frontend/src/pages/TeamSearchPage/index.tsx
- 전체 팀 조회 handler page 계산 수정
- 전체 모임 검색에서 결과가 없을 시 보여줄 empty state UI 구현
소피아가 이전 pr에서 전체 팀 조회 handler를 수정해주었던 것 같은데 반영이 안되어 있어서 다시 수정했습니다
현재 전체 모임 검색 시 결과가 없으면 early return을 해주고 있습니다. 검색 결과가 없을때도 search input이 보여야해서 이를 넣어주었습니다. 그래서 early return이 좋은 방법인가 라는 궁금증이 생기네요. 이에 대한 소피아의 의견이 궁금합니다( early return이 나을지 삼항 연산자가 나을지)
closed #306
=> feat: 전체 모임 검색에서 검색 결과가 없을 시 보여줄 empty state UI를 구현

frontend/src/pages/RollingpaperPage/components/LetterPaper.tsx, frontend/src/pages/RollingpaperPage/components/RollingpaperMessage.tsx, frontend/src/pages/RollingpaperPage/components/SecretMessage.stories.jsx, frontend/src/pages/RollingpaperPage/components/SecretMessage.tsx
- SecretMessage 컴포넌트 구현
- LetterPaper의 StyledMessageList에 스타일 추가
<br >
<br >
명세 논의 때 각 메시지마다 현재 사용자가 확인 가능한 메시지인가에 대한 정보(visible)를 받기로 했기 때문에, 
지금 RollingpaperMessage 컴포넌트가 해당 정보를 받으면 조건에 따라 SecrectMessage를 반환하는 방식으로 구현하면 좋겠다고 생각했습니다.
=> feat: 비밀글(비밀 메시지) UI 구현

frontend/src/App.tsx, frontend/src/api/team.ts, frontend/src/constants/index.ts, frontend/src/mocks/handlers/teamHandlers.js, frontend/src/pages/InvitePage/hooks/useCheckInviteLinkAccessibility.tsx, frontend/src/pages/InvitePage/hooks/useCheckLogin.tsx, frontend/src/pages/InvitePage/hooks/useCheckTeamJoined.tsx, frontend/src/pages/InvitePage/hooks/useJoinTeamWithInviteToken.tsx, frontend/src/pages/InvitePage/hooks/useTeamDetailWithInviteToken.tsx, frontend/src/pages/InvitePage/index.tsx, frontend/src/pages/KakaoRedirectPage/index.tsx, frontend/src/pages/LoginPage/index.tsx, frontend/src/pages/TeamDetailPage/components/InviteModal.tsx, frontend/src/pages/TeamDetailPage/components/NicknameCreateModalForm.tsx, frontend/src/pages/TeamDetailPage/hooks/useCreateInviteLink.tsx
- TeamDetail 페이지에서 초대링크 생성하기 기능 구현(inviteToken 생성)
- InvitePage에서 inviteToken을 이용한 모임 가입하기 기능 구현
- 사용자 로그인 여부, 해당 모임 가입 여부에 따라 페이지 접근 제한 기능 구현
- 이미 로그인한 사람
- 모임에 가입이 안 된 사람 → 초대링크 페이지를 바로 보여준다.
- 모임에 가입이 이미 된 사람 → alert(이미 가입한 모임입니다). → 해당 모임 페이지로 이동
- 로그인 안 한 사람
- 로그인 페이지로 redirect. → 로그인을 한다. (로그인 성공) → 초대링크 페이지로
→ 모임에 가입이 안 된 사람이면 초대링크 페이지를 보여준다.
→ 모임에 가입이 이미 된 사람이면 alert(이미 가입한 모임입니다.)하고 해당 모임 페이지로 이동
<br >
- 코멘트 남겨두겠습니다!
- 이번에 뭔가 작업 범위가 여기저기라,,, 정신없는 코드들이 좀 있는데 꼼꼼한 확인과 테스트 잘 부탁해요! 🥰
closed #340
=> feat: 초대 링크 관련 기능 구현

frontend/src/constants/index.ts, frontend/src/pages/RollingpaperCreationPage/components/MemberRollingpaperCreateForm.tsx, frontend/src/pages/RollingpaperCreationPage/components/RecipientBox.tsx, frontend/src/pages/RollingpaperCreationPage/components/TeamRollingpaperCreateForm.tsx, frontend/src/pages/RollingpaperCreationPage/hooks/useReadTeamMembers.tsx, frontend/src/pages/RollingpaperCreationPage/index.tsx, frontend/src/types/index.ts
- 모임, 개인을 선택해서 롤링페이퍼를 작성할 수 있도록 함
- RecipientType의 위치. 페이지 내에서만 사용되는 타입이라 이를 type폴더에 빼는 것이 맞을지 고민입니다. 오히려 RECIPIENT 상수와 같이 있는게 보기 더 편한 것 같기도 하고...??
- 모바일 위주로 구현하다보니 데스크탑 버전에서는 조금 공허함(단 이점은 기존에도 그랬어서 괜찮은 것 같기도 하구)
- 모임을 선택했다가 앗차 하고 뒤로 돌아갈 수 없음. 사용자가 뒤로가기를 눌렀을때 바로 팀 상세페이지로 가게 해도 괜찮을까에 대한 고민. 혹은 모임에 대한 롤링페이퍼를 작성중인지, 팀에 대한 롤링페이퍼를 작성중인지를 바로 알기 어려움. `회원가입`처럼 제목을 위에 써주는 것이 좋을까?
closed #345
=> feat: 모임/개인에게 롤링페이퍼 작성을 위한 UI를 구현

frontend/src/hooks/useParamValidate.tsx, frontend/src/hooks/useValidatedParam.tsx, frontend/src/pages/InvitePage/index.tsx, frontend/src/pages/RollingpaperCreationPage/components/MemberRollingpaperCreateForm.tsx, frontend/src/pages/RollingpaperCreationPage/components/TeamRollingpaperCreateForm.tsx, frontend/src/pages/RollingpaperPage/components/MessageBox.tsx, frontend/src/pages/RollingpaperPage/components/MessageCreateForm.tsx, frontend/src/pages/RollingpaperPage/hooks/useUpdateMessage.tsx, frontend/src/pages/RollingpaperPage/index.tsx, frontend/src/pages/TeamDetailPage/components/InviteModal.tsx, frontend/src/pages/TeamDetailPage/components/NicknameCreateModalForm.tsx, frontend/src/pages/TeamDetailPage/components/NicknameEditModalForm.tsx, frontend/src/pages/TeamDetailPage/components/RollingpaperList.tsx, frontend/src/pages/TeamDetailPage/index.tsx
- 메시지 작성 시 refetch
- 메시지 삭제 시 refetch
- 모임 참가 시 refetch
- rollingpaperId, teamId등을 query key로 사용하고 있습니다. 이때 초기에 사용하던 key 값은 타입이 string, refetch 시 사용하는 key 값은 타입이 number라 refetch가 일어나지 않았습니다.
- useParamValidate를 사용하면 useParams(react-router-dom)의 결과 값인 string이 반환됩니다. api hook에서 때로는 이 값을 number로 변환하여 받고, 이를 재사용하다보니 타입이 일치하지 않아 문제가 발생합니다. 따라서 이 값을 사용 할 때마다 type을 변환하는 것이 아닌, 값을 가져다쓸 때 타입을 지정할 수 있도록 수정하였습니다.
- useParamValidate는 type을 지정하여 받고, 이 타입으로 param을 return하도록 합니다. 이를 구현하며 생긴 고민은 이 T을 좁혀주어야 하는가입니다. 지금 생각했을 때는 number, string 타입만 사용할 것 같은데 이를 좁혀 주는 것이 좋을까요??(최근에 들었던 타입스크립트 강의가 신경쓰인달까요...?)
closed #369
=> feat: 누락된 refetch 해결

frontend/src/pages/MyPage/components/MessageList.tsx, frontend/src/pages/MyPage/components/RollingpaperList.tsx
- 받은 롤링페이퍼 리스트와 페이징의 높이를 고정
- 작성한 메시지 리스트와 페이징의 높이를 고정
closed #375
=> fea: 마이페이지의 paging 위치를 고정

backend/src/test/java/com/woowacourse/naepyeon/acceptance/AcceptanceTest.java, backend/src/test/java/com/woowacourse/naepyeon/acceptance/support/DatabaseCleaner.java, backend/src/test/java/com/woowacourse/naepyeon/repository/MemberRepositoryTest.java, backend/src/test/java/com/woowacourse/naepyeon/repository/MessageRepositoryTest.java, backend/src/test/java/com/woowacourse/naepyeon/repository/RollingpaperRepositoryTest.java, backend/src/test/java/com/woowacourse/naepyeon/repository/TeamParticipationRepositoryTest.java, backend/src/test/java/com/woowacourse/naepyeon/repository/TeamRepositoryTest.java, backend/src/test/java/com/woowacourse/naepyeon/service/AuthServiceTest.java, backend/src/test/java/com/woowacourse/naepyeon/service/MemberServiceTest.java, backend/src/test/java/com/woowacourse/naepyeon/service/MessageServiceTest.java, backend/src/test/java/com/woowacourse/naepyeon/service/RollingpaperServiceTest.java, backend/src/test/java/com/woowacourse/naepyeon/service/TeamServiceTest.java
close #410 
이제 acceptanceTest, 전체 테스트의 성능이 매우 빨라졌을 겁니다.
=> test: `AfterPropertiesSet`을 이용한 DB cleaner 클래스를 만들어 `@DirtiesContext` 제거

frontend/src/pages/RollingpaperPage/components/MessageBox.tsx, frontend/src/pages/RollingpaperPage/components/MessageTextArea.tsx
- 메시지 입력 시 줄의 마지막에서 스페이스를 눌러도 줄바꿈이 일어나지 않고 글자수만 늘어나게 됨
- 메시지 줄바꿈이 적용되지 않는 문제
- white-space: break-spaces;
- 연속 공백을 유지 및 문장의 끝부분 space 처리를 위해 break-spaces 사용
- 영어로 작성 시 화면 사이즈에 맞춰 줄바꿈이 되지 않는 문제
- word-break: break-all;
- 메시지 입력 시 줄의 마지막에서 스페이스를 눌러도 줄바꿈이 일어나지 않고 글자수만 늘어나게  되는 문제
- white-space: break-spaces;
closed #418
=> feat: 메시지 폼 관련 오류를 해결한다. 

frontend/src/api/team.ts, frontend/src/hooks/useInput.tsx, frontend/src/pages/TeamDetailPage/components/NicknameEditModalForm.tsx
- 닉네임 수정 모달 접속 시 기존의 닉네임을 보여주도록 수정
- 기존에 useQuery로 data만 가져올 시 hook으로 변경하지 않는 것 같아 이를 유지했습니다
- prop으로 defaultValue로 useInput의 기본 값을 받아 사용하기 위해 useEffect를 사용했는데요, 혹시 더 좋은 방법이 있을까요....?
closed #305
=> feat: 모임 프로필 설정 시 기존 모임 닉네임을 보여준다

frontend/src/components/LabeledInput.tsx, frontend/src/components/LabeledTextArea.tsx, frontend/src/constants/index.ts, frontend/src/pages/TeamCreationPage/hooks/useTeamCreationForm.tsx, frontend/src/pages/TeamCreationPage/index.tsx
- 모임 이름 정규식 수정
- 모든 문자 포함하도록 모임 이름 정규식 수정했습니다. 
- LabeledTextArea 글자 수 보여주기 UI 추가
- 우측 상단에서 입력한 글자 수를 보여주도록 했습니다.
- LabeledTextArea가 showValueLength(boolen, default는 false)을 prop으로 받아 조건부 렌더링 하도록 했습니다.
- LabeledTextArea css 수정
최대 100자인 것에 비해 기존 높이가 너무 작고, 줄바꿈하며 작성할 경우 scroll이 필요할 것으로 보여 관련 css 수정했습니다.
- LabeledTextArea css 수정과 글자 보여주기 추가된 부분에 대해서 지금 UI 괜찮은지 도리 의견 궁금합니다.
- 글자 수 보여주기 방식을 구현하는 더 좋은 방식이 있다면 제안 부탁합니다.
closed #415
=> refactor: 모임 추가하기 페이지 개선

frontend/src/pages/RollingpaperPage/components/LetterPaper.tsx, frontend/src/pages/RollingpaperPage/components/MessageBox.tsx, frontend/src/pages/RollingpaperPage/hooks/useMessageWrite.tsx, frontend/src/pages/RollingpaperPage/hooks/useSliceMessageList.tsx, frontend/src/pages/RollingpaperPage/index.tsx
- LetterPaper에서 렌더링할 요소의 목록에 MessageForm 컴포넌트를 함께 추가하여, 메시지 작성 시에도 새로운 메시지가 추가된 것과 같은 상황으로 정렬되도록 수정
<br >
<br >
- 맨 좌측 상단 배열에 MessageForm 컴포넌트가 추가된다.
- 가운데 배열, 우측 배열은 이동이 없다.
<br >
- 전체 메시지 목록에 MessageForm 컴포넌트를 추가한다.
- 모든 배열의 정렬이 오른쪽으로 한 칸씩 밀리는 방식으로 움직인다. (맨 우측에 위치한 경우 아래 칸 좌측으로 이동)
<br >
- 예상한 동작이 요 방식이 맞는지 확인해주세요.
- LetterPaper 내에 렌더링할 요소의 목록을 상태로 새로 정의했습니다. 우선은 LetterPaper의 요소들이라는 느낌으로,,, `elementList`라고 네이밍했는데 혹시 더 좋은 이름이 있다면 제안해주세요!
- elementList 관련한 동작들을 커스텀 훅으로 분리할까 싶었는데, 다른 커스텀 훅과 작업 범위(useSliceMessageList 관련)가 엮여있어서 조심스럽더라고요... 우선 LetterPaper에 대부분의 로직을 넣어뒀습니다. 어쨌든 리팩토링이 조금 더 필요할 것 같으니 어떤 방식이 좋을지 고민해볼게요. 도리도 보시고 아이디어 있으면 제안 부탁해요!
- 외에 다른 부분은 코멘트 남겨두겠습니다.
closed #416
=> refactor: MessageForm 추가될 때 메시지 정렬 방식 변경

frontend/src/api/index.ts, frontend/src/api/kakaoOauth.ts, frontend/src/api/member.ts, frontend/src/api/message.ts, frontend/src/api/rollingpaper.ts, frontend/src/api/team.ts, frontend/src/types/index.ts, frontend/src/util/ApiError.ts
- 커스텀 에러 ApiError 정의 (errorCode, message, errorHandler를 가짐)
- API layer 함수에서 에러 발생 시 try-catch 문으로 ApiError throw 하도록 구현
- Api layer 함수에 option으로 onError 인자를 넘길 수 있도록 추가
1. 호출된 api 함수는 api 요청을 보낸다. 이때 인자 option의 onError 속성으로 에러 핸들러와 함께 호출할 수 있다.
2. 요청 data를 받는 과정에서 에러 발생 시 catch 문에서 throw new ApiError로 커스텀 에러를 발생
- API layer 함수에 option을 추가하되, 기존에 호출문에서 수정없이 사용하도록 작성해봤습니다. 
일관성을 생각하면 API 함수의 첫 번째 인자는 api request에 들어갈 인자를 담은 객체, 두 번째 인자는 options 객체 이렇게 정리해봐도 좋을 것 같은데 도리 의견 궁금합니다! 
- 커스텀 에러 관련해서 작성한 타입이 적절한지 확인해주세요.
- catch문의 코드들이 반복되는데 어떻게 정리하면 좋을지 고민입니다. try-catch문을 템플릿처럼 쓸 수 있도록 공통 함수를 만들면 어떨까요?
closed #169
=> feat: API 커스텀 에러 적용

frontend/babel.config.js, frontend/jest.config.js, frontend/tsconfig.json, frontend/webpack.dev.js
- devtool: source-map으로 변경
- tsx? loader: ts-loader에서 ["babel-loader", "ts-loader"]로 변경
- jsx: react-jsx에서 preserve로 변경
<br >
dev mode 빌드 시 1. 타입 체크와 2. 리액트 문법 체크 둘 다 진행되도록 하고 싶었음.
tsx는 ts-loader, babel-loader 각각을 사용하는 두 단계를 거쳐 트랜스파일링 되도록 함.
1. **tsx는 ts-loader를 통해 타입이 제거된 jsx로 변환됨**
- tsconfig.json의 jsx: preserve로 tsx -> jsx로 변환되도록 설정 
https://www.typescriptlang.org/docs/handbook/jsx.html
- 이때 타입 체크가 진행됨.
2. **jsx는 babel-loader를 통해 js로 변환됨**
- 이때 리액트 문법 체크가 진행됨
babel-loader와 @babel/preset-react를 함께 사용하면 프리셋에 내장된 @babel/plugin-transform-react-jsx에서 리액트 문법 오류를 잡아준다.
=> refactor: tsconfig, webpack loader, devtool 변경

backend/src/main/java/com/woowacourse/naepyeon/repository/message/MessageRepositoryImpl.java, backend/src/test/java/com/woowacourse/naepyeon/repository/MessageRepositoryTest.java
close #473 
원인: totalCount가 현재 페이징된 메시지 번호 개수 (ex. 2페이지에 메시지 6~10번: 총 N개임에도 불구하고 N개가 아닌 10개라고 뜸.)
해결방법: Projections 스트림 count가 아닌 entity.count()하도록
=> fix: 작성한 메시지 개수를 해당페이지 개수로만 가져오는 버그 수정

frontend/src/pages/RollingpaperCreationPage/components/MemberRollingpaperCreateForm.tsx, frontend/src/pages/RollingpaperCreationPage/hooks/useReadTeamMembers.tsx
- 맴버 -> 멤버로 오타 수정
- useReadTeamMembers 훅에 onSuccess 인자 및 success handler추가
closed #482
=> fix: 롤링페이퍼 생성 페이지의 받는 사람 자동완성 기능 오류를 해결한다.

frontend/src/components/LabeledSwitch.tsx
LabeledSwitch의 색상을 제공하기 위해 사용하는 컴포넌트에 onChange없이 checked 속성을 사용하여 발생하는 문제 readOnly option을 추가하여 해결했습니다
closed #495
=> fix: LabeledSwitch에서 발생하는 경고를 해결

backend/src/main/java/com/woowacourse/naepyeon/repository/message/MessageRepositoryImpl.java, backend/src/test/java/com/woowacourse/naepyeon/acceptance/MemberAcceptanceTest.java, backend/src/test/java/com/woowacourse/naepyeon/repository/MessageRepositoryTest.java, backend/src/test/java/com/woowacourse/naepyeon/service/MessageServiceTest.java
close #494 
마이페이지에서 본인이 작성한 메시지 조회 시, 오래된 순으로 보여지는 불편한 점이 존재했습니다.
최신순으로 보여지도록 수정했습니다.
=> fix: 본인이 작성한 메시지 조회 시 최신순으로 정렬되도록 수정

frontend/src/pages/RollingpaperCreationPage/components/StepTitleWithLayout.tsx
- css 코드를 추가해서 스크롤바를 제거했습니다. 좌우, 상하 스크롤바 보이지는 않고 스크롤은 동작합니다.
모임 선택 스텝에서 수직 스크롤바까지 사라지는 부분이 아쉬운데요. 지금 구현 방식에서 overflow-x로 수평 스크롤을 제어하면 스텝단위로 넘어가는 액션이 동작하지 않아서 우선 임시로(?) 스크롤바를 모두 숨기는 방식으로 해봤습니다.
다른 방식 아시면 공유해주시고요!
이후에 여기 구조 개선하면 수직 스크롤바만 보이도록 할 수 있을 것 같아요.
closed #531
=> fix: 롤링페이퍼 만들기 페이지에서 보이는 불필요한 스크롤바를 제거한다.

frontend/src/pages/TeamDetailPage/components/TeamDescriptionBox.tsx
- 초대 하기, 모임 프로필 설정 버튼을 분리한다
closed #542
=> refactor: 모임 상세 페이지에서 초대하기, 모임 프로필 설정이 보이도록 한다.

frontend/src/pages/RollingpaperPage/hooks/useMessageBox.tsx
- 메시지 삭제 시 confirm 창을 띄우고, 확인을 눌렀을 때 삭제 요청이 가도록 수정했습니다.
삭제 버튼을 눌렀을 때, confirm 창이 뜨는 모습을 확인할 수 있습니다.
closed #563
=> feat: 메시지 삭제 전 confirm을 추가한다.

backend/docker/README.md, backend/docker/docker-compose.yml, backend/docker/replica/Dockerfile, backend/docker/replica/my.cnf, backend/docker/source/Dockerfile, backend/docker/source/my.cnf, backend/src/main/java/com/woowacourse/naepyeon/config/DataSourceConfig.java, backend/src/main/java/com/woowacourse/naepyeon/support/db/DatabaseType.java, backend/src/main/java/com/woowacourse/naepyeon/support/db/RoutingDataSource.java, backend/src/main/resources/application-deploy.yml, backend/src/main/resources/application-develop.yml, backend/src/main/resources/application-flywayTest.yml, backend/src/main/resources/application.yml, backend/src/test/resources/application.yml
일반적인 트랜잭션 로직에서는 Connection 객체를 먼저 확보하고 트랜잭션 동기화를 진행하는데
`@Transactional(readonly = true)`옵션에 따라 db를 분기하려면 트랜잭션 동기화를 먼저 마치고
해당 트랜잭션이 readOnly가 있냐 없냐에 따라 다른 Connection 객체를 가져야 하기 때문에 작업 순서를 변경해야 합니다.
그래서 트랜잭션 시작시에 Connection Proxy 객체를 리턴하고 실제 쿼리가 발생할 때 데이터 소스에서 올바른 Connection 객체를 얻도록
했습니다.
더 자세한 내용은 wiki로 작성해서 주말중에 업로드 하겠습니다!
close #435
=> feat: 데이터베이스 이중화 기능을 구현한다.

frontend/src/pages/MyPage/components/UserProfile.tsx
- 기존의 `handleEditSaveButtonClick`을 form의 submit handler로 주도록 변경했습니다. 이때 핸들러 이름을 `handleUserProfileEditFormSubmit`으로 변경했습니다.
- UserProfile 영역의 레이아웃을 정리했습니다. 불필요하게 감싸고 있는 div 태그를 정리하고, flex로 내부 컴포넌트의 정렬을 더 알아보기 쉽게 수정했습니다.
- 사용자 이름을 보여주는 영역, 사용자 이름을 수정하기 위한 Input의 크기를 키웠습니다. 사용자 이름 최대 길이가 길어지면서, 이름을 길게 작성하는 경우 UI가 어색해졌더라고요. 긴 사용자 이름에도 대응할 수 있도록, 해당 영역들의 가로 길이를 키웠고, 그 과정에서 수정 버튼을 아래로 보내봤습니다.
- 사용자 이름 변경을 테스트해보다가 UI가 어색해져서 같이 수정해봤는데요. 도리는 다른 의견일 수 있을 것 같아요. 확인해보고 의견주세요!
closed #565
=> fix: UserProfile에서 이름 수정 후 엔터를 눌렀을 때 새로고침 되는 버그를 해결한다.

frontend/src/api/team.ts, frontend/src/constants/index.ts, frontend/src/mocks/handlers/rollingpaperHandlers.js, frontend/src/pages/TeamDetailPage/components/RollingpaperList.tsx, frontend/src/pages/TeamDetailPage/hooks/useReadTeamRollingpaper.tsx, frontend/src/types/apiRequest.ts
- 모임 롤링페이퍼 조회 로직을 수정했습니다. 요청 url의 searchParams에 order와 filter를 추가했습니다.
- 모임 상세 페이지에서, order와 filter 상태를 추가하고 상태가 업데이트 되면 모임 롤링페이퍼 조회 요청을 refetch 하도록 했습니다.
- 로직을 먼저 정리하는 과정에서 기본 select, option 태그로 구현해봤습니다. 이후에 Select, Dropdown을 추가로 직접 구현할까 생각도 했는데요. **제 생각에는 기본 select, option 태그의 UI도 깔끔하고 괜찮아서 커스텀 컴포넌트를 따로 만들지는 않았어요.** 
저는 지금도 충분히 괜찮다고 생각합니다. **스타일을 더 주는 게 필요하다고 생각하는지, 준다면 어떤 스타일이 괜찮은지** 도리 의견 궁금합니다~
closed #516
=> feat: 롤링페이퍼 정렬/필터링 기능을 구현한다.

frontend/src/pages/MainPage/index.tsx, frontend/src/pages/TeamDetailPage/components/TeamJoinSection.tsx
- 사용자에게 혼란을 유발할 수 있는 안내 문구를 변경했습니다
- 메인 화면의 nav 버튼 문구들을 통일했습니다
closed #560
=> fix: 사용자 안내 문구를 변경한다.

frontend/src/assets/images/surprise-state.svg, frontend/src/pages/TeamDetailPage/components/EmptyTeamRollingpaper.tsx, frontend/src/pages/TeamDetailPage/components/RollingpaperList.tsx
- 팀에 작성된 롤링페이퍼가 없는 경우의 UI를 구현한다
closed #580
=> feat: 모임 상세 페이지 롤링페이퍼 empty state UI 구현

backend/build.gradle, backend/src/docs/asciidoc/errorCodes.adoc, backend/src/docs/asciidoc/notifications.adoc, backend/src/main/java/com/woowacourse/naepyeon/config/AuthenticationPrincipalConfig.java, backend/src/main/java/com/woowacourse/naepyeon/config/RedisConfig.java, backend/src/main/java/com/woowacourse/naepyeon/controller/NotificationController.java, backend/src/main/java/com/woowacourse/naepyeon/domain/notification/ContentType.java, backend/src/main/java/com/woowacourse/naepyeon/domain/notification/Notification.java, backend/src/main/java/com/woowacourse/naepyeon/exception/InvalidRedisMessageException.java, backend/src/main/java/com/woowacourse/naepyeon/exception/NotFoundNotificationException.java, backend/src/main/java/com/woowacourse/naepyeon/repository/notification/NotificationRepository.java, backend/src/main/java/com/woowacourse/naepyeon/repository/notification/NotificationRepositoryCustom.java, backend/src/main/java/com/woowacourse/naepyeon/repository/notification/NotificationRepositoryImpl.java, backend/src/main/java/com/woowacourse/naepyeon/service/MessageService.java, backend/src/main/java/com/woowacourse/naepyeon/service/NotificationService.java, backend/src/main/java/com/woowacourse/naepyeon/service/RollingpaperService.java, backend/src/main/java/com/woowacourse/naepyeon/service/dto/NotificationResponseDto.java, backend/src/main/java/com/woowacourse/naepyeon/service/dto/NotificationsResponseDto.java, backend/src/main/java/com/woowacourse/naepyeon/service/event/RollingpaperAndTeamIdEvent.java, backend/src/main/java/com/woowacourse/naepyeon/service/event/RollingpaperEvent.java, backend/src/main/resources/application-deploy.yml, backend/src/main/resources/application-develop.yml, backend/src/main/resources/application-flywayTest.yml, backend/src/main/resources/application.yml, backend/src/main/resources/db/migration/V0.5.2__notification.sql, backend/src/test/java/com/woowacourse/naepyeon/document/NotificationControllerTest.java, backend/src/test/java/com/woowacourse/naepyeon/document/TestSupport.java, backend/src/test/java/com/woowacourse/naepyeon/repository/NotificationRepositoryTest.java, backend/src/test/resources/application.yml
SSE와 redis를 활용하여 실시간 알림 기능을 구현했습니다.
현재 당사자에게 메시지가 작성되었을때, 모임에서 롤링페이퍼가 생성되었을때 알림이 가도록했습니다.
그러다 보니 해당 service에 notificationService가 참조되는 상황입니다.
그래서 알림이 실패하더라도 해당 메시지나 롤링페이퍼에 영향이 가지 않게  `@Transactional(propagation = Propagation.REQUIRES_NEW)`와 `@TransactionalEventListener`를 활용했습니다.
그리고 현재 테스트코드와 리팩토링을 하고있습니다. 그걸 다 진행하고 보내면 시간이 빠듯할거 같아서 보낸 후 수정하겠습니다.
추가적으로 수정할 내용은 다음과 같습니다.
+ 테스트 코드 추가
+ adoc 파일 작성
+ 커스텀 Exception 추가
+ 개발때 사용하던 log 지우기
close #592
=> feat: 실시간 알림 기능을 구현한다.

frontend/src/styles/reset.ts
- 아이폰에서 버튼 색상이 파란 색상으로 보이는 문제를 해결
closed #612
=> fix: 아이폰에서 버튼 색상이 파란색으로 보이는 문제를 해결

frontend/src/pages/RollingpaperCreationPage/components/Step2.tsx
- 롤링페이퍼 만들기 페이지의 Step2에서 isLoading를 isFetching으로 변경한다.
closed #617
=> fix: 롤링페이퍼 만들기 페이지에서 불필요한 Loading 컴포넌트가 보이는 버그를 해결한다.
