woowacourse-teams/2022-nae-pyeon

backend/README.md
backend/src/main/java/com/woowacourse/naepyeon/domain/Member.java
backend/src/main/java/com/woowacourse/naepyeon/domain/Message.java
backend/src/main/java/com/woowacourse/naepyeon/domain/Rollingpaper.java
backend/src/main/java/com/woowacourse/naepyeon/domain/Team.java
backend/src/main/java/com/woowacourse/naepyeon/domain/TeamMember.java
backend/src/test/java/com/woowacourse/naepyeon/NaepyeonApplicationTests.java

- 우아한테크코스 코드 포매터 적용
- Backend 환경설정 및 컨벤션 문서 작성

[BE] 백엔드 README 문서 작성 및 코드 컨벤션 적용

---

frontend/.storybook/main.js
frontend/.storybook/preview.js
frontend/jsconfig.json
frontend/package.json
frontend/src/App.tsx
frontend/src/components/Button.tsx
frontend/src/components/Header.tsx
frontend/src/components/IconButton.tsx
frontend/src/components/LabeledInput.tsx
frontend/src/components/PageTitle.tsx
frontend/src/components/SearchInput.tsx
frontend/src/pages/RollingpaperCreationPage.tsx
frontend/src/stories/Button.stories.jsx
frontend/src/stories/Header.stories.jsx
frontend/src/stories/IconButton.stories.jsx
frontend/src/stories/LabeledInput.stories.jsx
frontend/src/stories/PageTitle.stories.jsx
frontend/src/stories/SearchInput.stories.jsx
frontend/src/styles/reset.ts
frontend/tsconfig.json
frontend/webpack.config.js
frontend/yarn.lock

- 롤링페이퍼 이름을 입력할 수 있다
- 롤링페이퍼 대상을 검색할 수 있다
closed #16

feat: 롤링페이퍼 생성 페이지 UI 구현

---

frontend/src/App.tsx
frontend/src/components/IconButton.tsx
frontend/src/components/LetterPaper.tsx
frontend/src/components/RollingpaperMessage.tsx
frontend/src/pages/RollingpaperPage.tsx
frontend/src/stories/LetterPaper.stories.jsx
frontend/src/stories/RollingpaperMessage.stories.jsx

- 롤링페이퍼의 이름을 보여준다
- 롤링페이퍼 대상을 보여준다
- 롤링페이퍼 메시지 작성 버튼이 있다
- 작성된 메시지들을 보여준다
closed #17

feat: 롤링페이퍼 페이지 UI 구현

---

frontend/src/components/TextArea.tsx
frontend/src/pages/MessageWritePage.tsx
frontend/src/stories/TextArea.stories.jsx

- 메시지를 작성할 수 있다
- 메시지 작성 완료 버튼이 있다
closed #18

feat: 메시지 작성 페이지 UI 구현

---

.github/ISSUE_TEMPLATE/feature_request.md

+ feature 이슈에 대한 템플릿 작성
- 기능을 상세히
- 적는 곳
close #32

docs: feature 이슈 템플릿 작성

---

backend/src/main/java/com/woowacourse/naepyeon/config/WebConfig.java

```java
package com.woowacourse.naepyeon.config;
import org.springframework.context.annotation.Configuration;
import org.springframework.http.HttpHeaders;
import org.springframework.web.servlet.config.annotation.CorsRegistry;
import org.springframework.web.servlet.config.annotation.WebMvcConfigurer;
@Configuration
public class WebConfig implements WebMvcConfigurer {
public static final String ALLOWED_METHOD_NAMES = "GET,HEAD,POST,PUT,DELETE,TRACE,OPTIONS,PATCH";
@Override
public void addCorsMappings(final CorsRegistry registry) {
registry.addMapping("/**")
.allowedOrigins("*")
.allowedMethods(ALLOWED_METHOD_NAMES.split(","))
.exposedHeaders(HttpHeaders.LOCATION);
}
}
```
CORS 문제를 해결했습니다.
(allowedOrigins는 일단 /api 로 안하고 *로 해놓았어요)
close #38

chore: cors 문제 처리하는 로직 작성

---

frontend/src/components/RollingpaperMessageDetail.tsx
frontend/src/components/SearchInput.tsx
frontend/src/pages/MessageDetailPage.tsx
frontend/src/pages/MessageEditPage.tsx
frontend/src/pages/MessageWritePage.tsx
frontend/src/styles/reset.ts

- input에 focus in하면, 검색어 목록이 보인다.
- 검색어 항목 선택하면, 검색어 목록이 업데이트 된다.
- 검색어 목록에서 항목에 hover하면, 항목 배경 색상이 변경된다.

feat: SearchInput 컴포넌트를 보완

---

backend/src/main/java/com/woowacourse/naepyeon/controller/ControllerAdvice.java
backend/src/main/java/com/woowacourse/naepyeon/controller/dto/ErrorResponse.java
backend/src/main/java/com/woowacourse/naepyeon/controller/dto/MemberRegisterRequest.java
backend/src/main/java/com/woowacourse/naepyeon/controller/dto/MemberUpdateRequest.java
backend/src/main/java/com/woowacourse/naepyeon/controller/dto/MessageRequest.java
backend/src/main/java/com/woowacourse/naepyeon/controller/dto/MessageUpdateContentRequest.java
backend/src/main/java/com/woowacourse/naepyeon/controller/dto/RollingpaperCreateRequest.java
backend/src/main/java/com/woowacourse/naepyeon/controller/dto/TeamRequest.java
backend/src/main/java/com/woowacourse/naepyeon/exception/NaePyeonException.java
backend/src/main/java/com/woowacourse/naepyeon/exception/NotFoundMemberException.java
backend/src/main/java/com/woowacourse/naepyeon/exception/NotFoundMessageException.java
backend/src/main/java/com/woowacourse/naepyeon/exception/NotFoundRollingpaperException.java
backend/src/main/java/com/woowacourse/naepyeon/exception/NotFoundTeamException.java
backend/src/main/java/com/woowacourse/naepyeon/repository/JpaMessageRepository.java
backend/src/main/java/com/woowacourse/naepyeon/repository/JpaRollingpaperRepository.java
backend/src/main/java/com/woowacourse/naepyeon/service/MemberService.java
backend/src/main/java/com/woowacourse/naepyeon/service/MessageService.java
backend/src/main/java/com/woowacourse/naepyeon/service/RollingpaperService.java
backend/src/main/java/com/woowacourse/naepyeon/service/TeamService.java
backend/src/test/java/com/woowacourse/naepyeon/service/MemberServiceTest.java
backend/src/test/java/com/woowacourse/naepyeon/service/MessageServiceTest.java
backend/src/test/java/com/woowacourse/naepyeon/service/RollingpaperServiceTest.java
backend/src/test/java/com/woowacourse/naepyeon/service/TeamServiceTest.java

refactor: 정의한 커스텀 예외를 던지도록 변경

---

frontend/package.json
frontend/src/App.tsx
frontend/src/components/Button.tsx
frontend/src/mocks/handlers.js
frontend/src/pages/MessageDetailPage.tsx
frontend/src/pages/MessageEditPage.tsx
frontend/src/pages/MessageWritePage.tsx
frontend/src/pages/RollingpaperCreationPage.tsx
frontend/src/pages/RollingpaperPage.tsx
frontend/src/types/index.ts

feat: react query 적용

---

backend/src/main/java/com/woowacourse/naepyeon/TestDataInit.java
backend/src/main/java/com/woowacourse/naepyeon/domain/Member.java
backend/src/main/java/com/woowacourse/naepyeon/domain/Message.java
backend/src/main/java/com/woowacourse/naepyeon/domain/Rollingpaper.java
backend/src/main/java/com/woowacourse/naepyeon/domain/Team.java
backend/src/main/java/com/woowacourse/naepyeon/exception/DuplicateMemberEmailException.java
backend/src/main/java/com/woowacourse/naepyeon/exception/ExceedMemberPasswordLengthException.java
backend/src/main/java/com/woowacourse/naepyeon/exception/ExceedMemberUsernameLengthException.java
backend/src/main/java/com/woowacourse/naepyeon/exception/ExceedMessageContentLengthException.java
backend/src/main/java/com/woowacourse/naepyeon/exception/ExceedRollingpaperNameLengthException.java
backend/src/main/java/com/woowacourse/naepyeon/exception/ExceedTeamNameLengthException.java
backend/src/main/java/com/woowacourse/naepyeon/exception/InvalidMemberEmailException.java
backend/src/main/java/com/woowacourse/naepyeon/exception/InvalidMemberPasswordException.java
backend/src/main/java/com/woowacourse/naepyeon/exception/InvalidMemberUsernameException.java
backend/src/test/java/com/woowacourse/naepyeon/domain/MemberTest.java
backend/src/test/java/com/woowacourse/naepyeon/domain/MessageTest.java
backend/src/test/java/com/woowacourse/naepyeon/domain/RollingpaperTest.java
backend/src/test/java/com/woowacourse/naepyeon/domain/TeamTest.java
backend/src/test/java/com/woowacourse/naepyeon/repository/MessageRepositoryTest.java
backend/src/test/java/com/woowacourse/naepyeon/repository/RollingpaperRepositoryTest.java
backend/src/test/java/com/woowacourse/naepyeon/repository/TeamMemberRepositoryTest.java
backend/src/test/java/com/woowacourse/naepyeon/service/MessageServiceTest.java
backend/src/test/java/com/woowacourse/naepyeon/service/RollingpaperServiceTest.java
backend/src/test/java/com/woowacourse/naepyeon/service/TeamServiceTest.java

feat: 도메인에 대한 검증과 도메인 테스트를 추가한다.

---

frontend/.storybook/preview.js
frontend/src/components/Button.tsx
frontend/src/components/LineButton.tsx
frontend/src/components/TextArea.tsx
frontend/src/pages/MessageEditPage.tsx
frontend/src/pages/MessageWritePage.tsx
frontend/src/pages/RollingpaperCreationPage.tsx
frontend/src/stories/Button.stories.jsx
frontend/src/stories/LetterPaper.stories.jsx
frontend/src/stories/LineButton.stories.jsx

- LineButton component 구현
- Button component 구현
closed #73

feat: button 디자인

---

frontend/src/components/LabeledInput.tsx
frontend/src/components/LabeledRadio.tsx
frontend/src/components/LabeledTextArea.tsx
frontend/src/pages/TeamCreationPage.tsx
frontend/src/stories/LabeledRadio.stories.jsx
frontend/src/stories/LabeledTextArea.stories.jsx

- labeledRadio 컴포넌트를 구현한다
- labeledTextArea 컴포넌트를 구현한다
- 모임 추가하기 페이지 UI를 구현한다
closed #76

feat: 모임 생성 페이지 UI

---

backend/src/main/java/com/woowacourse/naepyeon/controller/TeamController.java
backend/src/main/java/com/woowacourse/naepyeon/controller/dto/RollingpaperCreateRequest.java
backend/src/main/java/com/woowacourse/naepyeon/controller/dto/TeamRequest.java
backend/src/main/java/com/woowacourse/naepyeon/domain/Member.java
backend/src/main/java/com/woowacourse/naepyeon/domain/Team.java
backend/src/main/java/com/woowacourse/naepyeon/domain/TeamMember.java
backend/src/main/java/com/woowacourse/naepyeon/service/TeamService.java
backend/src/main/java/com/woowacourse/naepyeon/service/dto/TeamResponseDto.java
backend/src/test/java/com/woowacourse/naepyeon/acceptance/TeamAcceptanceTest.java
backend/src/test/java/com/woowacourse/naepyeon/domain/MessageTest.java
backend/src/test/java/com/woowacourse/naepyeon/domain/RollingpaperTest.java
backend/src/test/java/com/woowacourse/naepyeon/domain/TeamTest.java
backend/src/test/java/com/woowacourse/naepyeon/repository/MessageRepositoryTest.java
backend/src/test/java/com/woowacourse/naepyeon/repository/RollingpaperRepositoryTest.java
backend/src/test/java/com/woowacourse/naepyeon/repository/TeamMemberRepositoryTest.java
backend/src/test/java/com/woowacourse/naepyeon/repository/TeamRepositoryTest.java
backend/src/test/java/com/woowacourse/naepyeon/service/MessageServiceTest.java
backend/src/test/java/com/woowacourse/naepyeon/service/RollingpaperServiceTest.java
backend/src/test/java/com/woowacourse/naepyeon/service/TeamServiceTest.java

feat: 모임 엔티티 변경 및 모임 추가 API 변경, 모임 조회 DTO 변경

---

backend/src/main/java/com/woowacourse/naepyeon/controller/ControllerAdvice.java
backend/src/main/java/com/woowacourse/naepyeon/controller/dto/ErrorResponse.java
backend/src/main/java/com/woowacourse/naepyeon/controller/dto/MemberRegisterRequest.java
backend/src/main/java/com/woowacourse/naepyeon/controller/dto/MemberUpdateRequest.java
backend/src/main/java/com/woowacourse/naepyeon/controller/dto/MessageRequest.java
backend/src/main/java/com/woowacourse/naepyeon/controller/dto/MessageUpdateContentRequest.java
backend/src/main/java/com/woowacourse/naepyeon/controller/dto/RollingpaperCreateRequest.java
backend/src/main/java/com/woowacourse/naepyeon/controller/dto/RollingpaperUpdateRequest.java
backend/src/main/java/com/woowacourse/naepyeon/controller/dto/TeamRequest.java
backend/src/main/java/com/woowacourse/naepyeon/exception/DuplicateMemberEmailException.java
backend/src/main/java/com/woowacourse/naepyeon/exception/ExceedMemberPasswordLengthException.java
backend/src/main/java/com/woowacourse/naepyeon/exception/ExceedMemberUsernameLengthException.java
backend/src/main/java/com/woowacourse/naepyeon/exception/ExceedMessageContentLengthException.java
backend/src/main/java/com/woowacourse/naepyeon/exception/ExceedRollingpaperNameLengthException.java
backend/src/main/java/com/woowacourse/naepyeon/exception/ExceedTeamNameLengthException.java
backend/src/main/java/com/woowacourse/naepyeon/exception/InvalidMemberEmailException.java
backend/src/main/java/com/woowacourse/naepyeon/exception/InvalidMemberPasswordException.java
backend/src/main/java/com/woowacourse/naepyeon/exception/InvalidMemberUsernameException.java
backend/src/main/java/com/woowacourse/naepyeon/exception/NaePyeonException.java
backend/src/main/java/com/woowacourse/naepyeon/exception/NotFoundMemberException.java
backend/src/main/java/com/woowacourse/naepyeon/exception/NotFoundMessageException.java
backend/src/main/java/com/woowacourse/naepyeon/exception/NotFoundRollingpaperException.java
backend/src/main/java/com/woowacourse/naepyeon/exception/NotFoundTeamException.java
backend/src/test/java/com/woowacourse/naepyeon/repository/TeamMemberRepositoryTest.java

예외응답 폼 변경했습니다!
errorCode와 message를 각각 반환하도록 변경했어요!
close #89

feat: 예외 응답 폼 변경

---

frontend/src/App.tsx
frontend/src/components/Header.tsx
frontend/src/components/LabeledInput.tsx
frontend/src/constants/index.ts
frontend/src/mocks/handlers.js
frontend/src/pages/SignUpPage.tsx

- 회원가입 페이지 UI
- 회원가입 요청 및 API mocking
closed #79

feat: 회원가입 페이지를 구현

---

frontend/src/App.tsx
frontend/src/components/Header.tsx
frontend/src/components/PageContainer.tsx
frontend/src/components/PageTitle.tsx
frontend/src/pages/MessageDetailPage.tsx
frontend/src/pages/MessageEditPage.tsx
frontend/src/pages/MessageWritePage.tsx
frontend/src/pages/RollingpaperCreationPage.tsx
frontend/src/pages/RollingpaperPage.tsx
frontend/src/pages/SignUpPage.tsx
frontend/src/pages/TeamCreationPage.tsx

- 공통된 페이지 레이아웃 추가 구현
closed #93

feat: 공통된 페이지 레이아웃 추가

---

frontend/src/api/index.ts
frontend/src/components/LabeledRadio.tsx
frontend/src/constants/index.ts
frontend/src/pages/MessageDetailPage.tsx
frontend/src/pages/MessageEditPage.tsx
frontend/src/pages/MessageWritePage.tsx
frontend/src/pages/RollingpaperCreationPage.tsx
frontend/src/pages/RollingpaperPage.tsx
frontend/src/pages/SignUpPage.tsx
frontend/src/pages/TeamCreationPage.tsx

- axios instance 생성 및 컴포넌트에 적용
- baseURL 상수화

refactor: axios instance 적용

---

frontend/src/App.tsx
frontend/src/components/MainCard.tsx
frontend/src/components/PlusButton.tsx
frontend/src/pages/MainPage.tsx
frontend/src/stories/MainCard.stories.jsx
frontend/src/stories/PlusButton.stories.jsx

- 모임 Card 컴포넌트 구현
- 모임 추가 버튼 구현

feat: main page UI 구현

---

frontend/src/pages/SignUpPage.tsx

- 회원가입 요청 핸들러 로직 수정
close #118

feat: 회원가입 페이지의 회원가입 요청 핸들러 로직 수정

---

backend/src/main/java/com/woowacourse/naepyeon/controller/TeamController.java
backend/src/main/java/com/woowacourse/naepyeon/domain/TeamParticipation.java
backend/src/main/java/com/woowacourse/naepyeon/exception/DuplicateTeamNameException.java
backend/src/main/java/com/woowacourse/naepyeon/exception/DuplicateTeamPaticipateException.java
backend/src/main/java/com/woowacourse/naepyeon/exception/ExceedNicknameLengthException.java
backend/src/main/java/com/woowacourse/naepyeon/repository/JpaTeamMemberRepository.java
backend/src/main/java/com/woowacourse/naepyeon/repository/JpaTeamRepository.java
backend/src/main/java/com/woowacourse/naepyeon/repository/TeamMemberRepository.java
backend/src/main/java/com/woowacourse/naepyeon/repository/TeamRepository.java
backend/src/main/java/com/woowacourse/naepyeon/repository/jpa/TeamJpaDao.java
backend/src/main/java/com/woowacourse/naepyeon/repository/jpa/TeamMemberJpaDao.java
backend/src/main/java/com/woowacourse/naepyeon/service/TeamService.java
backend/src/main/java/com/woowacourse/naepyeon/service/dto/TeamResponseDto.java
backend/src/main/java/com/woowacourse/naepyeon/service/dto/TeamsResponseDto.java
backend/src/test/java/com/woowacourse/naepyeon/acceptance/AcceptanceFixture.java
backend/src/test/java/com/woowacourse/naepyeon/acceptance/TeamAcceptanceTest.java
backend/src/test/java/com/woowacourse/naepyeon/repository/TeamParticipationRepositoryTest.java
backend/src/test/java/com/woowacourse/naepyeon/service/TeamServiceTest.java

모임과 모임가입 관련 조회기능이랑 예외처리 등이 많이 빠져있는걸 인수테스트 목록별로 작성하다 알게 되었습니다.
빠진 기능 및 테스트코드 작성했으니 리뷰 잘 부탁드려요!
close #107

feat: 모임관련 기능 추가 및 인수테스트 보강

---

frontend/src/App.tsx
frontend/src/api/index.ts
frontend/src/components/Header.tsx
frontend/src/components/RequireLogin.tsx
frontend/src/components/RequireLogout.tsx
frontend/src/context/UserContext.tsx
frontend/src/mocks/handlers.js
frontend/src/pages/ErrorPage.tsx
frontend/src/pages/LoginPage.tsx
frontend/src/pages/MainPage.tsx
frontend/src/pages/MessageDetailPage.tsx
frontend/src/pages/MessageEditPage.tsx
frontend/src/pages/MessageWritePage.tsx
frontend/src/pages/RollingpaperCreationPage.tsx
frontend/src/pages/RollingpaperPage.tsx
frontend/src/pages/SignUpPage.tsx
frontend/src/pages/TeamCreationPage.tsx
frontend/src/pages/TeamDetailPage.tsx
frontend/src/pages/TeamSearchPage.tsx
frontend/src/util/cookie.ts

- UserContext
- cookie 설정
- 로그인 상태에 따른 라우팅 로직 추가

feat: 로그인 유저 정보 관련 로직 구현

---

backend/src/main/java/com/woowacourse/naepyeon/controller/RollingpaperController.java
backend/src/main/java/com/woowacourse/naepyeon/service/RollingpaperService.java

refactor: 롤링페이퍼 컨트롤러 메서드명 및 파라미터명 변경

---

frontend/src/components/LabeledTextArea.tsx
frontend/src/components/TeamRollingpaperList.tsx
frontend/src/constants/index.ts
frontend/src/pages/LoginPage.tsx
frontend/src/pages/MainPage.tsx
frontend/src/pages/MessageDetailPage.tsx
frontend/src/pages/MessageEditPage.tsx
frontend/src/pages/MessageWritePage.tsx
frontend/src/pages/RollingpaperCreationPage.tsx
frontend/src/pages/RollingpaperPage.tsx
frontend/src/pages/SignUpPage.tsx
frontend/src/pages/TeamCreationPage.tsx
frontend/src/pages/TeamDetailPage.tsx
frontend/src/pages/TeamSearchPage.tsx
frontend/src/types/index.ts

- API 요청 후 에러 응답이 돌아오면 alert
- 유효하지 않은 형식의 입력값에 대한 처리를 추가
closed #130

feat: API 에러 응답 처리 및 form 입력 유효성 검사를 추가한다

---

frontend/src/components/LabeledTextArea.tsx
frontend/src/pages/TeamCreationPage.tsx

feat: 모임 생성시 닉네임을 받도록 수정

---

backend/src/main/java/com/woowacourse/naepyeon/domain/TeamParticipation.java
backend/src/main/java/com/woowacourse/naepyeon/service/TeamService.java
backend/src/test/java/com/woowacourse/naepyeon/domain/RollingpaperTest.java

refactor: 디미터 법칙 준수^^

---

frontend/src/pages/MessageDetailPage.tsx

fix: message 삭제 시 작성된 롤링페이퍼로 이동

---

frontend/src/App.tsx
frontend/src/pages/LoginPage.tsx
frontend/src/pages/MainPage.tsx
frontend/src/pages/MessageDetailPage.tsx
frontend/src/pages/MessageEditPage.tsx
frontend/src/pages/MessageWritePage.tsx
frontend/src/pages/RollingpaperCreationPage.tsx
frontend/src/pages/RollingpaperPage.tsx
frontend/src/pages/SignUpPage.tsx
frontend/src/pages/TeamCreationPage.tsx
frontend/src/pages/TeamDetailPage.tsx
frontend/src/pages/TeamSearchPage.tsx

- RequireLogin, RequireLogout 컴포넌트의 로직이 page 단위의 컴포넌트보다 먼저 실행되도록 하기 위해, 
page 컴포넌트 내부에서 사용하는 것이 아니라, page 컴포넌트를 감싸도록 수정
closed #152

fix: RequireLogin, RequireLogout 컴포넌트 사용 위치 변경

---

frontend/package.json

chore: package.json script 변경

---

backend/src/main/resources/application-deploy.yml

환경변수 받아서 쓰는 배포용 설정파일 추가
close #158

chore: deploy 설정파일 추가

---

backend/src/main/java/com/woowacourse/naepyeon/controller/MessageController.java
backend/src/main/java/com/woowacourse/naepyeon/controller/dto/MessageRequest.java
backend/src/main/java/com/woowacourse/naepyeon/domain/Member.java
backend/src/main/java/com/woowacourse/naepyeon/domain/Message.java
backend/src/main/java/com/woowacourse/naepyeon/exception/NotAuthorException.java
backend/src/main/java/com/woowacourse/naepyeon/service/MessageService.java
backend/src/main/java/com/woowacourse/naepyeon/service/RollingpaperService.java
backend/src/test/java/com/woowacourse/naepyeon/acceptance/AcceptanceFixture.java
backend/src/test/java/com/woowacourse/naepyeon/acceptance/MessageAcceptanceTest.java
backend/src/test/java/com/woowacourse/naepyeon/repository/MemberRepositoryTest.java
backend/src/test/java/com/woowacourse/naepyeon/repository/MessageRepositoryTest.java
backend/src/test/java/com/woowacourse/naepyeon/service/MessageServiceTest.java

+ 403 Forbidden
+ 2003: 해당 글의 작성자가 아닙니다.
두가지 이슈를 동시에 해결 했습니다.
close #106
close #150

feat: 메시지 인수 테스트 추가 및 메시지 닉네임 보이게 수정

---

.gitignore
frontend/package.json
frontend/src/api/index.ts
frontend/src/constants/index.ts
frontend/webpack.dev.js
frontend/webpack.prod.js

- dotenv를 설정한다
- dev, prod 모드의 webapack 설정한다
closed #188

feat: webpack과 dotenv 설정

---

frontend/src/api/index.ts
frontend/src/components/Header.tsx
frontend/src/components/UserProfile.tsx
frontend/src/context/UserContext.tsx
frontend/src/mocks/handlers/memberHandlers.js
frontend/src/pages/LoginPage.tsx
frontend/src/util/cookie.ts

- 로그인 API mocking 수정
- 내 정보 조회 API mocking 추가
- userContext에 memberId 추가
- 자동 로그인 시 내 정보 조회 추가
closed #200

feat: 로그인 로직 수정

---

frontend/src/pages/TeamCreationPage/index.tsx

feat: 모임 색상 선택 변경

---

frontend/src/components/Header.tsx

feat: 마이페이지 버튼 클릭 시 mypage로 라우팅 추가

---

frontend/src/pages/RollingpaperCreationPage/index.tsx
frontend/src/pages/RollingpaperPage/index.tsx
frontend/src/pages/TeamDetailPage/components/RollingpaperList.tsx
frontend/src/pages/TeamDetailPage/index.tsx

- useQuery에 사용하는 query keys 배열 업데이트

refactor: useQuery에 사용하는 query keys 업데이트

---

frontend/src/components/Header.tsx

- header sticky 추가
- header 배경 투명도 추가
closed #227

feat: header sticky 추가

---

frontend/src/constants/index.ts
frontend/src/pages/RollingpaperCreationPage/index.tsx

- 롤링페이퍼 제목 유효성 검사 추가
- 롤링페이퍼 생성 폼의 입력값 유효 여부에 따라, 제출 버튼 disabled 추가
- 롤링페이퍼 생성 페이지의 input label Text 변경
closed #226

feat: 롤링페이퍼 생성 폼 유효성 검사 구현

---

frontend/src/pages/RollingpaperPage/components/LetterPaper.tsx
frontend/src/pages/RollingpaperPage/components/RollingpaperMessage.tsx

- 메시지 수정 오류 해결
수정할 메시지 선택 시 필요한 값들을 변경하는 handler함수를 추가하였습니다.
closed #245

feat: 메시지 수정 오류 해결

---

frontend/src/components/Paging.tsx
frontend/src/pages/MyPage/index.tsx
frontend/src/pages/TeamSearchPage/index.tsx

- Paging component 명세에 맞도록 수정
- MyPage page 관련 state 초기값 0으로 갖도록 수정
- TeamSearchPage의 infinte scroll page 초기값을 0으로 수정
closed #243

feat: Pagination API 명세와 관련된 컴포넌트 로직 수정

---

frontend/src/components/Dropdown.tsx
frontend/src/components/Header.tsx
frontend/src/components/Modal.tsx

- Dropdown의 z index를 수정한다
- Header의 z index를 수정한다
- Modal, Dimmer의 z index를 수정한다 
closed #252

feat: Header z index 수정

---

frontend/src/api/team.ts
frontend/src/mocks/dummy/myTeams.json
frontend/src/mocks/handlers/teamHandlers.js
frontend/src/pages/MainPage/index.tsx
frontend/src/pages/TeamSearchPage/index.tsx

- 명세에 맞도록 내 모임 가져오기 mocking 수정
- 메인 페이지에 infinte scroll 추가
closed #258

feat: 메인 페이지에 Infinte scroll을 추가한다

---

frontend/src/pages/MainPage/index.tsx

- myTeam에 type을 추가
- mainPage type오류 해결
closed #269

feat: myTeam type 추가로 오류 해결

---

frontend/src/pages/RollingpaperPage/components/LetterPaper.tsx

- 메시지 수정 시 색상을 전달하도록 한다
closed #273

feat: message 수정 요청에 색상 추가

---

frontend/src/api/team.ts
frontend/src/pages/TeamSearchPage/index.tsx

- 무한 스크롤이 적용된 API 중 초기 pageParam이 1인 경우, 0으로 변경
- 모임 검색 요청 query key 변경
- 모임 검색 요청 API 파일 분리
오류 있었던 부분이라 테스트 한번 부탁합니다~
closed #278

fix: 페이지네이션이 적용된 API 요청에서 발생하는 오류 해결

---

frontend/src/pages/RollingpaperPage/components/LetterPaper.tsx
frontend/src/pages/RollingpaperPage/components/MessageForm.tsx
frontend/src/pages/RollingpaperPage/components/MessageTextArea.tsx

- 메시지 작성 취소 아이콘은 x로 변경한다
- 작성하는 글자수가 보일 수 있도록 한다

feat: MessageForm 컴포넌트의 작성 취소 아이콘을 변경하고 수정시 글자수가 나오도록 수정

---

frontend/src/mocks/handlers/teamHandlers.js
frontend/src/pages/LoginPage/index.tsx
frontend/src/pages/MainPage/components/MyTeamCard.tsx

1. 로그인 페이지. 페이지 영역 밖으로 벗어나는 오류 (Nest Hub, 1024 x 600)
- 수정 전
- 수정 후
<br >
2. 메인 페이지. 가입한 모임 목록에서 모임 카드가 목록 영역 밖으로 벗어나는 오류 (Samsung Galaxy S8+, 360 x 740)
- 수정 전
- 수정 후
3. 메인 페이지의 가입한 모임 조회 요청 핸들러 로직에 오류가 있어 함께 수정했습니다.
closed #284

fix: 반응형 UI 오류 수정

---

frontend/src/pages/RollingpaperPage/components/RollingpaperMessage.tsx

- 메시지 삭제 시 confirm을 추가
closed #298

feat: 메시지 삭제 confirm 추가

---

frontend/src/constants/index.ts
frontend/src/pages/MyPage/components/UserProfile.tsx
frontend/src/pages/RollingpaperCreationPage/index.tsx
frontend/src/pages/TeamDetailPage/components/TeamNicknameModalForm.tsx

- 명세에 맞도록 이름 조건을 수정 (1~64자 모든 글자)
- 명세에 맞도록 팀 닉네임 조건을 수정 (2~20자 모든 글자)
깃... 어렵네요
closed #271

feat: 명세에 맞도록 사용자 이름과 모임 닉네임 조건을 수정

---

frontend/src/pages/RollingpaperPage/components/RollingpaperMessage.tsx

- 충분히 긴 닉네임이 메시지에 모두 보일 수 있도록 style 수정
closed #304

feat: 긴 닉네임이 메시지에 나올 수 있도록 style 수정

---

frontend/src/App.tsx
frontend/src/api/index.ts
frontend/src/api/member.ts
frontend/src/components/RequireLogin.tsx
frontend/src/components/RequireLogout.tsx
frontend/src/context/UserContext.tsx
frontend/src/hooks/useAutoLogin.tsx
frontend/src/index.tsx
frontend/src/util/cookie.ts

- RequireLogin, RequireLogout Outlet 사용하도록 수정
- 자동 로그인 로직 추가(useAutoLogin)
closed #314

fix: 초기 사용자 정보 요청 API 호출 순서 오류를 수정

---

frontend/src/api/member.ts
frontend/src/api/message.ts
frontend/src/api/rollingpaper.ts
frontend/src/api/team.ts
frontend/src/hooks/useAutoLogin.tsx
frontend/src/hooks/useParamValidate.tsx
frontend/src/pages/MyPage/components/UserProfile.tsx
frontend/src/pages/MyPage/index.tsx
frontend/src/pages/RollingpaperCreationPage/index.tsx
frontend/src/pages/RollingpaperPage/components/LetterPaper.tsx
frontend/src/pages/RollingpaperPage/components/RollingpaperMessage.tsx
frontend/src/pages/RollingpaperPage/index.tsx
frontend/src/pages/TeamCreationPage/index.tsx
frontend/src/pages/TeamDetailPage/components/NicknameCreateModalForm.tsx
frontend/src/pages/TeamDetailPage/components/NicknameEditModalForm.tsx
frontend/src/pages/TeamDetailPage/components/RollingpaperList.tsx
frontend/src/pages/TeamDetailPage/components/TeamDescriptionBox.tsx
frontend/src/pages/TeamDetailPage/index.tsx
frontend/src/pages/TeamSearchPage/index.tsx
frontend/src/types/index.ts

- appClient를 사용하는 API 관련 코드를 분리한다
closed #333

feat: API 관련 코드를 분리

---

frontend/src/pages/TeamDetailPage/components/InviteModal.tsx

- 초대링크 URL에 누락된 'invite' path 추가
closed #357

fix: 잘못된 초대링크 수정

---

frontend/src/api/rollingpaper.ts
frontend/src/components/AutoCompleteInput.tsx
frontend/src/hooks/useAutoCompleteInput.tsx
frontend/src/mocks/handlers/rollingpaperHandlers.js
frontend/src/pages/RollingpaperCreationPage/components/MemberRollingpaperCreateForm.tsx
frontend/src/pages/RollingpaperCreationPage/components/TeamRollingpaperCreateForm.tsx
frontend/src/pages/RollingpaperCreationPage/hooks/useCreateMemberRolliingpaper.tsx
frontend/src/pages/RollingpaperCreationPage/hooks/useCreateTeamRollingpaper.tsx
frontend/src/pages/RollingpaperCreationPage/hooks/useReadTeamMembers.tsx

- 모임에게 롤링페이퍼 작성하기 기능 추가 (useCreateTeamRollingpaper)
- 멤버에게 롤링페이퍼 작성하기 기능 추가 (useCreateMemberRollingpaper)
- AutoCompleteInput 컴포넌트 수정
- AutoCompleteList 위치 변경
- useAutoCompleteList 수정 (e.preventDeault 제거)
closed #356

feat: 모임 롤링페이퍼 추가 기능을 추가

---

backend/src/main/java/com/woowacourse/naepyeon/repository/jpa/MessageJpaDao.java
backend/src/test/java/com/woowacourse/naepyeon/acceptance/MemberAcceptanceTest.java

refactor: 메세지 조회시 모임 대상도 조회할 수 있도록 수정

---

frontend/src/components/LineButton.tsx
frontend/src/pages/InvitePage/index.tsx

- LineButton에 disabled 스타일 추가 구현
- 초대링크 가입 폼에 닉네임 유효성 검사 추가
<br >
<br >
closed #368

fix: 초대링크로 가입에 닉네임 유효성 검사 추가

---

.github/workflows/ci-backend.yml
.github/workflows/ci-frontend.yml

+ 기존 jenkins ci를 github action으로 이전
+ 머지 완료 후 jenkins에서 기존 ci 삭제 예정
close #377

feat: github action ci를 구현한다.

---

.github/workflows/sonarqube.yml
backend/build.gradle

close #343 
sonarqube PR -> 머지 이후 테스트 커버리지, 변경분의 code smells, bugs 분석. 전체 코드 분석 안하고 변경분만 분석합니다. 따라서 현재 bot에서 보내주는 리포트는 변경분(build.gradle, yml 만 변경했으므로 bugs, smells가 없습니다.)
main, develop 머지 시 -> 전체 코드 분석합니다.
sonarqube DB를 h2에서 postgreDB로 변경했습니다.

feat: sonarqube 연동

---

frontend/src/pages/RollingpaperPage/components/MessageBox.tsx
frontend/src/pages/RollingpaperPage/components/MessageCreateForm.tsx
frontend/src/pages/RollingpaperPage/index.tsx

- build시 발생하는 error를 해결한다
closed #383

fix: build error 해결

---

.github/workflows/sonarqube.yml

close #389 
해당 현상 방지를 위해 적용했습니다.

fix: `.github`변경은 소나큐브 분석 무시하도록 변경

---

frontend/src/pages/TeamDetailPage/components/NicknameCreateModalForm.tsx

- 모임 참여시 refetch 안되는 문제 해결
closed #399

feat: 모임 참여시 refetch 안되는 문제 해결

---

backend/src/main/resources/log4j2.yml

feat: main 부분을 합친다.

---

backend/src/main/java/com/woowacourse/naepyeon/service/TeamService.java

hotfix: inviteJoin시 Transactional 관련 버그를 수정한다.

---

frontend/package.json
frontend/src/App.tsx
frontend/tsconfig.json
frontend/webpack.common.js
frontend/webpack.prod.js

- react lazy를 사용한 code splitting
closed #426

refactor: 초기 접속 시 불러오는 스크립트 리소스 사이즈를 줄이기

---

frontend/public/index.html
frontend/src/styles/font.ts

- head에 font preload 추가
- font face에 font-display: swap 추가
closed #428

refactor: font preload 및 로드 시 시스템 글꼴 일시적 표시 추가

---

.github/workflows/ci-frontend.yml
.gitignore
frontend/package.json
frontend/src/pages/RollingpaperPage/components/LetterPaper.tsx
frontend/tsconfig.json
frontend/webpack.common.js
frontend/webpack.dev.js
frontend/webpack.prod.js

- webpack.dev devtool 변경
- tsconfig sourceMap 변경
- loader 및 package script 수정
closed #440

chore: package, webpack, tsconfig 설정 파일을 변경

---

frontend/src/App.tsx
frontend/src/api/googleOauth.ts
frontend/src/constants/index.ts
frontend/src/index.tsx
frontend/src/mocks/handlers/memberHandlers.js
frontend/src/pages/GoogleRedirectPage/index.tsx
frontend/src/pages/LoginPage/index.tsx
frontend/src/types/apiRequest.ts

- google oAuth 로그인 구현
- goole oAuth 로그인 리다이렉트 페이지 추가
전반적으로 kakaoOAuth와 유사한 로직입니다.
아직 백엔드가 머지가 안되서 테스트는 어려울 수 있습니다.
closed #445

feat: google oauth 구현

---

backend/src/main/resources/application-develop.yml

close #462 
queryDSL pr 머지 -> 해당 pr 머지 -> 인덱스 pr 머지 순으로 부탁드립니다.

feat: develop.yml에서 flyway enabled true로 변경

---

backend/src/main/resources/application-develop.yml

그냥 톰캣 관련 설정값 다 젠킨스에서 환경변수로 넣는 걸로 합시다!
close #466

chore: 개발서버 설정파일 수정

---

frontend/public/index.html
frontend/src/pages/LoginPage/index.tsx

- Google 로그인 버튼에서 준비 중 alert를 띄운다.
- Google 로그인 관련 meta data를 제거한다.
closed #465

feat: Google 로그인 버튼 기능을 준비 중으로 변경

---

backend/src/main/java/com/woowacourse/naepyeon/repository/message/MessageRepositoryImpl.java
backend/src/test/java/com/woowacourse/naepyeon/repository/MessageRepositoryTest.java

fix: 작성한 메시지 개수를 해당페이지 개수로만 가져오는 버그 수정 - 리팩터링 필요

---

backend/src/main/java/com/woowacourse/naepyeon/repository/message/MessageRepository.java
backend/src/main/java/com/woowacourse/naepyeon/repository/message/MessageRepositoryCustom.java
backend/src/main/java/com/woowacourse/naepyeon/repository/message/MessageRepositoryImpl.java

fix: 잘못된 querydsl JPQL로 임시로 변환

---

frontend/src/api/googleOauth.ts
frontend/src/api/index.ts
frontend/src/api/kakaoOauth.ts
frontend/src/api/member.ts
frontend/src/api/message.ts
frontend/src/api/rollingpaper.ts
frontend/src/api/team.ts

- requestApi 함수 내에 catch문 제거
- api 함수들 전체 리팩토링
api 요청 함수들이 전반적으로 수정되었으니 dev 서버로 동작 테스트 부탁합니다!
closed #472

refactor: requestApi 함수를 수정한다.

---

frontend/src/App.tsx
frontend/src/pages/ErrorPage/index.tsx

- error fallback page 구현
closed #471

feat: error page 수정

---

README.md

docs: 백엔드 프로젝트 기술을 추가한다

---

backend/src/docs/asciidoc/rollingpapers.adoc
backend/src/main/java/com/woowacourse/naepyeon/controller/RollingpaperController.java
backend/src/main/java/com/woowacourse/naepyeon/domain/rollingpaper/Recipient.java
backend/src/main/java/com/woowacourse/naepyeon/domain/rollingpaper/Rollingpaper.java
backend/src/main/java/com/woowacourse/naepyeon/repository/rollingpaper/RollingpaperRepositoryCustom.java
backend/src/main/java/com/woowacourse/naepyeon/repository/rollingpaper/RollingpaperRepositoryImpl.java
backend/src/main/java/com/woowacourse/naepyeon/service/RollingpaperService.java
backend/src/test/java/com/woowacourse/naepyeon/document/RollingpaperControllerTest.java
backend/src/test/java/com/woowacourse/naepyeon/repository/RollingpaperRepositoryTest.java
backend/src/test/java/com/woowacourse/naepyeon/service/RollingpaperServiceTest.java

close #493 
```bash
GET /api/v1/teams/{teamId}/rollingpapers?order="latest"&filter="team" HTTP/1.1
headers: {
Authorization: `Bearer ${accessToken}`
}
```

feat: 롤링페이퍼 정렬 api 구현

---

frontend/src/App.tsx
frontend/src/pages/MainPage/components/MyTeamsSection.tsx
frontend/src/pages/MyTeamPage/hooks/useReadMyTeams.tsx
frontend/src/pages/MyTeamPage/index.tsx

- 메인페이지에서 내편들 더보기 버튼을 누를 때 이동하는 페이지입니다
- 무한스크롤로 페이징이 되도록 하였습니다
closed #518

feature: 가입한 모임 목록 페이지 구현

---

backend/src/main/java/com/woowacourse/naepyeon/repository/teamparticipation/TeamParticipationRepositoryImpl.java

teamPaticipation에서 team타고 조회하는데 teamPaticipation 의 id로 desc 한줄 추가했습니당
close #529

feat: 가입한 팀 조회시 최근 가입 순으로 정렬

---

frontend/src/pages/RollingpaperCreationPage/components/RecipientBox.tsx

- 모임/멤버 롤링페이퍼 선택 UI 문구를 업데이트했습니다.
closed #540

refactor: 롤링페이퍼 생성 플로우 UI를 개선한다.

---

backend/src/main/java/com/woowacourse/naepyeon/repository/messagelike/MessageLikeRepository.java
backend/src/main/java/com/woowacourse/naepyeon/service/MessageService.java
backend/src/test/java/com/woowacourse/naepyeon/service/MessageServiceTest.java

close #544 
메세지 삭제지 메세지 좋아요 기록도 삭제하도록 추가하였습니다.

feat: 메세지 삭제지 메세지 좋아요 기록도 삭제

---

backend/src/main/java/com/woowacourse/naepyeon/repository/message/MessageRepositoryImpl.java
backend/src/test/java/com/woowacourse/naepyeon/repository/MessageRepositoryTest.java

close #545 
- 해당 역할을 프론트에서 백으로 위임

feat: 롤링페이퍼 조회 시 메시지 순서를 오래된 순에서 최신 순으로 변경한다

---

frontend/src/pages/RollingpaperPage/components/LetterPaper.tsx

- 메시지 목록 역순 정렬하던 코드를 제거했습니다.
closed #549

feature: 롤링페이퍼 내 메시지 정렬 순서를 변경한다. 

---

frontend/src/pages/LoginPage/index.tsx
frontend/src/pages/RollingpaperCreationPage/components/Step1.tsx

- 모바일에서 가려지는 OAuth 로그인 버튼이 보이도록 위치를 변경한다.
- 모바일 버전의 롤링페이퍼 생성 나의 팀 보기 레이아웃을 변경한다.

fix: UI 오류를 해결한다.

---

backend/src/main/java/com/woowacourse/naepyeon/repository/rollingpaper/RollingpaperRepositoryImpl.java
backend/src/test/java/com/woowacourse/naepyeon/acceptance/MemberAcceptanceTest.java
backend/src/test/java/com/woowacourse/naepyeon/repository/RollingpaperRepositoryTest.java
backend/src/test/java/com/woowacourse/naepyeon/service/RollingpaperServiceTest.java

feat: 나의 롤링페이퍼를 오래된 순에서 최신 순으로 변경한다

---

frontend/src/components/IconButton.tsx
frontend/src/components/PageTitleWithBackButton.tsx
frontend/src/components/Snackbar.tsx
frontend/src/constants/index.ts
frontend/src/pages/RollingpaperPage/components/LetterPaper.tsx
frontend/src/pages/RollingpaperPage/components/Like.tsx
frontend/src/pages/RollingpaperPage/components/MessageBox.tsx
frontend/src/pages/RollingpaperPage/components/MessageColorPicker.tsx
frontend/src/pages/RollingpaperPage/components/MessageForm.tsx
frontend/src/pages/RollingpaperPage/hooks/useMessageForm.tsx
frontend/src/pages/TeamCreationPage/index.tsx

feat: 웹 접근성을 개선한다

---

frontend/src/pages/TeamDetailPage/components/RollingpaperList.tsx
frontend/src/pages/TeamDetailPage/index.tsx

- 모임 내 롤링페이퍼가 없을 시 롤링페이퍼 생성 버튼 추가
closed #597

fix: 누락된 롤링페이퍼 생성 버튼 추가

---

frontend/src/components/Paging.tsx

- Paging의 스타일을 수정한다
closed #600

fix: Paging의 스타일을 수정한다

---

backend/src/main/java/com/woowacourse/naepyeon/service/MessageService.java
backend/src/main/java/com/woowacourse/naepyeon/service/NotificationService.java
backend/src/main/java/com/woowacourse/naepyeon/service/RollingpaperService.java
backend/src/main/java/com/woowacourse/naepyeon/service/event/RollingpaperAndAuthorIdEvent.java
backend/src/main/java/com/woowacourse/naepyeon/service/event/RollingpaperAndTeamIdAndAuthorIdEvent.java

본인이 작성한 메시지, 롤링페이퍼에는 알림을 받지 않게
분기처리를 추가했습니다.

refactor: 본인이 작성한 메시지, 롤링페이퍼에는 알림을 받지 않게 수정

---

frontend/src/pages/RollingpaperCreationPage/hooks/useCreateMemberRolliingpaper.tsx

- 멤버 롤링페이퍼 생성 시 화면 이동이 되지 않던 문제를 해결함
closed #605

fix: 멤버 롤링페이퍼 생성 시 화면 이동하도록 한다

---

frontend/src/pages/MainPage/components/MyTeamsSection.tsx
frontend/src/pages/MainPage/components/ReceivedRollingpapersSection.tsx
frontend/src/pages/MyPage/components/MessageList.tsx
frontend/src/pages/MyPage/components/RollingpaperList.tsx
frontend/src/pages/MyPage/index.tsx
frontend/src/pages/MyTeamPage/index.tsx
frontend/src/pages/NotificationPage/index.tsx
frontend/src/pages/RollingpaperCreationPage/components/Step2.tsx
frontend/src/pages/RollingpaperPage/index.tsx
frontend/src/pages/TeamDetailPage/components/NicknameEditModalForm.tsx
frontend/src/pages/TeamDetailPage/components/RollingpaperList.tsx
frontend/src/pages/TeamDetailPage/index.tsx
frontend/src/pages/TeamSearchPage/index.tsx

- 서버 요청 데이터가 없는 경우 Loading UI를 보여준다.
closed #607

refactor: 서버 요청 데이터가 없는 경우 Loading UI를 보여준다

---

frontend/src/pages/TeamSearchPage/index.tsx

- padding 값 수정
- 페이지 타이틀 추가
closed #579

refactor: 모임 검색하기 페이지 UI를 개선한다.

---

backend/src/main/resources/application-deploy.yml
backend/src/main/resources/application-develop.yml

feat: 커넥션풀 사이즈 환경변수를 복제 서버 DB에 맞게 나눈다.

---

frontend/src/components/LabeledSwitch.tsx
frontend/src/components/Modal.tsx
frontend/src/pages/TeamDetailPage/components/InviteModal.tsx

- 아이폰 모달창 UI 오류를 해결한다
- 비공개 모임 소개 문구를 수정한다
closed #615

fix: 모바일 UI 오류를 해결한다

---

frontend/src/pages/RollingpaperCreationPage/hooks/useSteps.tsx

- ios에서 롤링페이퍼 생성 페이지에서 발생하는 오류를 해결
closed #620

fix: ios 롤링페이퍼 만들기 progressBar 오류 수정

---

frontend/src/components/Badge.tsx
frontend/src/mocks/dummy/notifications.json
frontend/src/pages/NotificationPage/index.tsx

- 알림 페이지에 스크롤을 적용한다.
- 알림 Badge UI를 개선한다.
closed #622

fix: 알림 관련 UI를 개선한다.

---

frontend/src/constants/index.ts

- 일시적으로 accessToken 만료 시간을 늘린다.
- 1800 -> 36000
closed #624

fix: accessToken 만료 시간을 늘린다.
